Changed minstret to (hopefully) correctly count retired instructions.
openhwgroup/cv32e40x pull request #116
Opened 2021-06-30 12:01 UTC by silabs-oysteink

Halting EX stage in case of minstret/h read in EX and any valid instruction in WB.
Halting to get correct value for reading minstret to GPR.

No errors for CSR minstret checks in ci_check.

Not SEC clean

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-06-30 13:11 UTC, silabs-halfdan approved these changes
Conceptually this means defining the minstret update as a side-effect of the instruction rather than an update happening between instructions.
I would say this is ok if clearly specified/documented.

2021-06-30 13:13 UTC, Silabs-ArjanB requested changes

2021-06-30 13:13 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +                      ) && instr_valid && !ctrl_fsm_i.halt_ex;
Make ID and EX stage consistent. In ID the halt signal is factored into instr_valid.
This relates to the todo on line 103 in the original EX stage module. That todo needs to be understood first before this PR gets fixed/merged

2021-06-30 13:13 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  logic        minstret_stall;        // Stall due to minstret/h read in EX
Can't this just be part of csr_stall? I see now that csr_stall still stall ID whereas this new stall stalls EX. In the future, when both stall EX, they should get merged, so you can ignore this remark for now.

2021-06-30 13:13 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .csr_raddr_o                ( csr_raddr_ex           ),
The CSR module outputs use inconsistent names; we can clean that up later (don't know a good naming strategy for this yet; can you just add a todo?)

2021-06-30 13:13 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mhpmevent.minstret = ex_wb_pipe_i.instr_valid && !exception_in_wb && !ctrl_fsm_o.kill_wb && !ctrl_fsm_o.halt_wb; // todo: Should maybe use wb_stage local instr_valid, as the curre
Yes, please use local instr_valid and then exclude instructions which should never count as retired (ecall, etc.)

2021-06-30 13:14 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +                      ) && instr_valid && !ctrl_fsm_i.halt_ex;
Ah, yes I will make them consistent

2021-06-30 13:15 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic        minstret_stall;        // Stall due to minstret/h read in EX
Agreed. The csr_stall currently does not check csr_addr, for ID stage that is still a part of operand_b, so it felt better to use EX stage for this as that actually has a concept of csr_addr.

2021-07-01 07:53 UTC, silabs-oysteink commented
Closing PR, as the current implementation is very fragile  and requires some more updates.

2021-07-01 07:53 UTC, closed without merging