Multiplier SVAs valid/ready update
openhwgroup/cv32e40x pull request #132
Opened 2021-07-05 14:23 UTC by silabs-robin

Formal regression was failing, so I took the opportunity to fix the multiplier SVAs that appear outdated after valid/ready handshaking was introduced.
Three things are changed: 1) "s_insistent_valid" replaces antecedent of input stability assertions, 2) "a_check_result_constant" was similarly updated, 3) a_check_acc_mul_value_zero was qualified with valid_i.

NB! This needs review before merging. (doesn't seem like uarch multiplier section reflects latest changes?)

Question: Should we deal with those 2 TODOs too?

2021-07-05 14:52 UTC, Silabs-ArjanB commented on sva/cv32e40x_mult_sva.sv
>    // TODO:low This assertion will soon be purposely broken as valid_i could be deasserted to abort ongoing multicyle instructions
Can you fix the TODOs as well now that you are updating this file?

2021-07-06 16:40 UTC, silabs-robin commented on sva/cv32e40x_mult_sva.sv
>    // TODO:low This assertion will soon be purposely broken as valid_i could be deasserted to abort ongoing multicyle instructions
I have fixed the 2 TODOs

----

> assign mulh_result_valid = valid_i && (operator_i == MUL_H) && ready_o; // TODO:low could valid_o be used directly here?

Not only "could" but I think it should/must.
`ready_o` before and after introducing ready/valid handshake protocol are identical in name, not identical in semantics.
Previously, it meant both "ready for new upstream inputs" _and_ "output can be used".
I think the only reason the assertions still worked is because incidentally `ready_o` is implied by some conditions relating to `valid_o`.
`valid_o` is the qualifier of outputs.

> This assertion [a_enable_constant_when_mulh_active] will soon be purposely broken

Previously `enable_i` had a stability requirement.
`valid_i` does not have such a requirement (afaik).
Hence I deleted this stale commented-away assertion.

----

I also added two new assertions.
If these are objectionable then I can remove them again.
First, `valid_o |-> valid_i` because mult doesn't register its inputs and the output validity therefore demands input validity.
Secondly, `(valid_o && ready_i) |-> ready_o` because the result has been consumed and we don't want to waste performance.

2021-07-07 11:43 UTC, silabs-oivind requested changes
Please add check for valid_o in a_mul_result. It should be set immediately on single cycle multiplications.

2021-07-07 12:53 UTC, silabs-robin commented
> Please add check for valid_o in a_mul_result. It should be set immediately on single cycle multiplications.

I added that now.
Although I split it into a new assertion because it is supposedly easier for the tool.

2021-07-07 13:12 UTC, silabs-oivind approved these changes

2021-07-07 14:31 UTC, merged