Shifter cleanup
openhwgroup/cv32e40x pull request #140
Opened 2021-07-15 14:16 UTC by silabs-halfdan

Cleaned up and simplified shifter.

SEC clean both with B_EXT==NONE and with B_EXT==ZBA_ZBB_ZBS.

### Area
#### B_EXT==ZBA_ZBB_ZBS
Showing total area below for the following:

- Before (master)
- With the two clean-up commits only (i.e. excluding the move of decoding logic to the decoder)
- After, with all changes in this branch

```
                   Area    Branch
Before:           30393u  (master)
W/clean-up only:  30349u  (n/a)
After:            30472u  (shifter_cleanup)
```

#### B_EXT==NONE
With the B-extension disabled we see a slight area improvement:
```
         Area    Branch
Before: 28821u  (master)
After:  28801u  (shifter_cleanup)
```

2021-07-15 15:11 UTC, Silabs-ArjanB requested changes

2021-07-15 15:11 UTC, Silabs-ArjanB commented on rtl/cv32e40x_b_decoder.sv
> +              decoder_ctrl_o.alu_operator               = ALU_B_ROR;
Is it the goal to eventually remove ALU_B_ROR and other shifter based operations from alu_operator?

2021-07-15 15:11 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +    logic        operand_tieoff;
The tieoff line needs a comment; what is the supposed effect of the tieoff?

2021-07-16 07:27 UTC, silabs-halfdan commented on rtl/cv32e40x_b_decoder.sv
> +              decoder_ctrl_o.alu_operator               = ALU_B_ROR;
Yes, that would be ideal, I will do a separate PR for that.

2021-07-16 07:52 UTC, Silabs-ArjanB approved these changes

2021-07-16 07:52 UTC, merged