Path cleanup for bypass module
openhwgroup/cv32e40x pull request #164
Opened 2021-08-04 11:10 UTC by silabs-oysteink

-Changed rf_we_o in EX to _not_ factor in halt and kill, as this would
lead to hazards not being detected during halt. Not SEC clean as stalls are affected by this fix.

-Added a rf_we_wb_raw output to the WB stage for use in the bypass module.
-Not including the local instr valid in WB stage lsu_en and lsu_valid_o.

The above two changes are done to prevent timing paths like
controller_fsm -> bypass -> controller_fsm.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-08-04 11:10 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> -    .lsu_en_wb_i                 ( lsu_en_wb_i              ),
This signal is not used in the controller FSM

2021-08-04 11:11 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
>    assign lsu_valid_o = lsu_en_gated;
This change is SEC clean standalone.

2021-08-04 13:25 UTC, Silabs-ArjanB requested changes

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +  logic        rf_we_wb_raw; // Unaffected by kill/halt
Rename to rf_we_raw_wb;

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .rf_we_wb_raw_o             ( rf_we_wb_raw                 ),
Rename:

.rf_we_raw_wb_o ( rf_we_raw_wb ),

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .rf_we_wb_i                     ( rf_we_wb_raw           ),
Rename:

.rf_we_wb_i ( rf_we_raw_wb ),

Later (or now) we can maybe also rename the .rf_we_wb_i to .rf_we_raw_wb_i

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  output logic          rf_we_wb_raw_o, // Raw rf_we, not affected by kill/halt
Rename

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_en_gated = ex_wb_pipe_i.lsu_en && ex_wb_pipe_i.instr_valid;
Naming is not consistent: lsu_en_gated and rf_we_wb_raw_o have similar gating (both with registered instr_valid), but there names are quite different. I believe that in other stages we use _gated to refer to gating with the local instr_valid. I think both signals should just be called lsu_en_raw_o and rf_we_raw_o (also drop the _wb as that is obvious and that suffix will be used for the core level signals). The qualification with the registered instr_valid can then be done inside the bypass module (as I believe it is doing for other signals as well).

2021-08-04 13:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign rf_we_wb_raw_o = ex_wb_pipe_i.rf_we && ex_wb_pipe_i.instr_valid; // Used for hazard detection, must be kept stable regardless of kill/halt
assign rf_we_raw_o = ex_wb_pipe_i.rf_we;

Or maybe this is not needed at all as ex_wb_pipe_i as a whole can just be used inside the bypass module.

2021-08-05 12:55 UTC, Silabs-ArjanB approved these changes

2021-08-05 12:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  //  assign wb_ready_o = ctrl_fsThankm_i.kill_wb || (lsu_ready_i && !ctrl_fsm_i.halt_wb);
Typing incident it seems; will be cleaned up later as part of todo

2021-08-05 12:55 UTC, merged