Made B_EXT a top level parameter
openhwgroup/cv32e40x pull request #173
Opened 2021-08-10 15:05 UTC by silabs-halfdan

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-08-10 16:32 UTC, Silabs-ArjanB requested changes

2021-08-10 16:32 UTC, Silabs-ArjanB commented on bhv/cv32e40x_wrapper.sv
> +  parameter B_EXT                        = NONE,
This should have the b_ext_e type as well

2021-08-11 07:18 UTC, silabs-halfdan commented on bhv/cv32e40x_wrapper.sv
> +  parameter B_EXT                        = NONE,
ah yes...

2021-08-11 10:03 UTC, Silabs-ArjanB approved these changes

2021-08-11 10:03 UTC, merged