RVFI debug updates
openhwgroup/cv32e40x pull request #177
Opened 2021-08-11 14:26 UTC by silabs-halfdan

Added debug mode and debug cause signal, renamed rvfi_dbg signal to rvfi_debug to match spec.

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-08-11 14:57 UTC, Silabs-ArjanB requested changes
See comments

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   input logic [2:0]                          debug_cause_i,
debug_cause_i is not available in the RTL so it should not be an input here; it should be constructed in the RVFI module

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   output logic [ 0:0]                        rvfi_debug,
Duplicate signal; now called rvfi_dbg_mode

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   output logic [ 0:0]                        rvfi_dbg_mode,
Remove [0:0]

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +      rvfi_debug         <= '0;
Remove rvfi_debug everywhere

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_dbg_cause <= debug_cause_i;
Cause needs to be constructed in the RVFI module

2021-08-11 14:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_dbg_mode  <= debug_mode_i;
Discuss with Øystein whether 'debug mode' needs to get constructed inside RVFI or whether you can import it from the RTL.

2021-08-13 12:39 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +   input logic [2:0]                          debug_cause_i,
ctrl_fsm.debug_cause contains the debug cause. Discussed the use of this signal with Øystein and using it should be ok as long as it is only sampled during the DEBUG_TAKEN state of the controller FSM.

2021-08-13 12:43 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_dbg_mode  <= debug_mode_i;
Discussed this with Øystein, probing it in IF to allow any un-killed LSU instructions to complete will give us the correct result.

2021-08-13 12:43 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_dbg_cause <= debug_cause_i;
Will update these signals.

2021-08-13 12:44 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +      rvfi_debug         <= '0;
Will do

2021-08-13 15:19 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_dbg_mode  <= debug_mode_i;
If you do this, please add clear explanation in your code.

2021-08-13 15:20 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   input logic [2:0]                          debug_cause_i,
I am not sure about whether these signals are the same; sent you a more detailed note about it.

2021-08-16 11:16 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
Won't this give the wrong cause is debug was entered due to an external request (code 0x3) while at the same time an ebreak (with lower priority) was in WB? I would think we might need to qualify with checking if we are in debug mode as well.

2021-08-16 11:23 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
An ebreak in wb should be killed (suppressing the ebreak_in_wb signal) if we get an external request at the same time.

2021-08-16 11:27 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
> An ebreak in wb should be killed (suppressing the ebreak_in_wb signal) if we get an external request at the same time.

I think this was addresses at my first (then edited) comment? Ebreak are in fact a higher priority debug cause than an external haltreq (I mistakenly thought the other way around in my first comment), so in that case the ebreak would 'win'.  I think the only concern was the trigger match, which as mentioned will suppress any special instruction bits.

2021-08-16 11:37 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
These comments got a bit messy with edits, we discussed it offline and will leave this code as is.

2021-08-16 12:00 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
Maybe just add some more comments to clarify why it is safe, ie ebreak with trigger match will never be signalled as ebreak_in_wb for instance.

2021-08-16 12:02 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +          debug_cause_if_next <=  ebreak_in_wb_i ? 3'h1 : debug_cause_i; // Debug entry from debug mode caused by EBREAK is not captured by debug_cause_i
Ok, will add a comment

2021-08-16 12:27 UTC, silabs-oysteink approved these changes

2021-08-16 14:29 UTC, Silabs-ArjanB requested changes

2021-08-16 14:29 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mode      <= current_priv_lvl_i;
Can you add a todo here to indicate that an explanation (or fix) is needed to explain why current_priv_lvl_i is valid when sampled here? (Now this signal is constant, so it doesn't matter, but this might likely break when user mode is added)

2021-08-16 14:30 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mode      <= current_priv_lvl_i;
Good point, I'll add it now.

2021-08-16 14:57 UTC, Silabs-ArjanB approved these changes

2021-08-16 14:57 UTC, merged