Implemented LSU bus errors, excluding controller updates.
openhwgroup/cv32e40x pull request #19
Opened 2021-03-26 13:12 UTC by silabs-oysteink

SEC equivalent with 1e35b273a8364a3a283df80f8bed9e09b8857ffb (No functional change, only 'plumbing')

2021-03-29 07:10 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +    // will not have data dependency on loaded data (NMI should happen before this store)
That is not really needed in my opinion. It is however important that such following store (or load) if it also receives a bus error, will not update data_addr_wb_o. The NMI can be taken later if needed.

2021-03-29 07:12 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +      if(!(block_addr_wb_i || data_err_wb_o) && (trans_valid && trans_ready)) begin
Why do you use 'data_err_wb_o' here? I would think that its value should already be included by the controller into the value of block_addr_wb_i,

2021-03-29 07:15 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller.sv
> +  output logic        block_addr_wb_o,            // To LSU to prevent data_addr_wb_i updates between error and taken NMI
I understand why you named it like this, but I do think it is a bit misleading (as it makes it seem that this is an output of the WB stage. Can you rename it to block_data_addr_o? Same renaming in other files. Of course the new name is also a bit misleading as it doesn't block the propagation of data_addr into EX, just its propagation into WB.

2021-03-29 07:16 UTC, Silabs-ArjanB requested changes
See comments

2021-03-30 07:22 UTC, silabs-oysteink commented on rtl/cv32e40x_load_store_unit.sv
> +      if(!(block_addr_wb_i || data_err_wb_o) && (trans_valid && trans_ready)) begin
You're right, I'll remove it.

2021-03-30 07:27 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> +  output logic        block_addr_wb_o,            // To LSU to prevent data_addr_wb_i updates between error and taken NMI
Renamed

2021-03-30 07:39 UTC, silabs-oysteink commented on rtl/cv32e40x_load_store_unit.sv
> +    // will not have data dependency on loaded data (NMI should happen before this store)
A store with dependencies on a load with bus errors may use an undefined result as part of the address, and could be a potential security risk. I updated the comment to clarify this.

2021-03-30 07:44 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +    // will not have data dependency on loaded data (NMI should happen before this store)
Agreed

2021-03-30 07:49 UTC, Silabs-ArjanB requested changes
See comments

2021-03-30 07:49 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .block_addr_wb_i       ( block_addr_wb      ),
This seems to be dangling now. Can this be changed into: .block_data_addr_i ( block_data_addr ),

2021-03-30 07:55 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    .block_addr_wb_i       ( block_addr_wb      ),
Fixed

2021-03-30 08:47 UTC, Silabs-ArjanB approved these changes

2021-03-30 08:47 UTC, merged