Bugfix: Incorrect CSR stall for mret
openhwgroup/cv32e40x pull request #235
Opened 2021-09-17 13:41 UTC by silabs-oysteink

CSR stall logic did not take into account mret implicit writes when mret was in EX stage.

Removed dret from CSR stall logic as a dret kills the whole pipeline when it is in WB,
and thus no hazard from that.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-09-17 14:47 UTC, Silabs-ArjanB requested changes

2021-09-17 14:47 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_bypass.sv
> +  assign csr_write_in_ex_wb = ((id_ex_pipe_i.instr_valid && (id_ex_pipe_i.csr_en || id_ex_pipe_i.mret_insn)) ||
The lack of brackets and the ordering of signals is a bit confusing in the above.

Can it be replaced by the following (if that is equivalent):

  assign csr_write_in_ex_wb = (
      (id_ex_pipe_i.instr_valid && (id_ex_pipe_i.csr_en || id_ex_pipe_i.mret_insn)) ||
      (ex_wb_pipe_i.instr_valid && (ex_wb_pipe_i.csr_en || ex_wb_pipe_i.mret_insn))
  );

2021-09-17 15:00 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  assign csr_write_in_ex_wb = ((id_ex_pipe_i.instr_valid && (id_ex_pipe_i.csr_en || id_ex_pipe_i.mret_insn)) ||
Very much agreed, fixed :)

2021-09-20 06:44 UTC, Silabs-ArjanB approved these changes

2021-09-20 06:45 UTC, merged