RVFI: Fixed lint warnings and fixed issue with pma register assignment
openhwgroup/cv32e40x pull request #243
Opened 2021-09-24 13:22 UTC by silabs-halfdan

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-09-24 13:45 UTC, Silabs-ArjanB requested changes

2021-09-24 13:45 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  // pmpmseccfg[1] not supported
- Can you add a todo here as this CSR should actually actually exist, but might be always 0; either way it should be connected to the RTL and not tied off here.
- Also add a todo to change pmpmseccfg[0] into mseccfg and pmpmseccfg[1] into mseccfgh (which are the official names for these CSRs) in both RVFI and the RTL (or just do the renaming now)

2021-09-24 13:57 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +  // pmpmseccfg[1] not supported
Will make some small updates and add todos.

2021-09-24 14:16 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +  // pmpmseccfg[1] not supported
Implementing these small changes instead of adding todos here. Will add todo in 40s for mseccfgh probe hookup.

2021-09-27 07:13 UTC, Silabs-ArjanB approved these changes

2021-09-27 07:13 UTC, merged