New event for minstret counter.
openhwgroup/cv32e40x pull request #248
Opened 2021-09-29 10:06 UTC by silabs-oysteink

Instead of using wb_valid which factors in data_rvalid_i,
minstret is counted for the first cycle of a valid instruction in WB.
For LSU instructions with stalls on rvalid, this means we count before the instruction retires.
RVFI is altered to detect this and report correct values for the retired instruction.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-09-29 10:49 UTC, silabs-oivind commented on rtl/cv32e40x_controller_fsm.sv
> +
This will be used for multiple events, not only minstret. Could you pick a more generic name? E.g. wb_valid_event ?
Could also create a common signal to be used in the counter events, factoring in kill_wb and halt_wb.
Should wb_minstret_event also be cleared if WB is killed?

2021-09-29 11:00 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +
Good point, I'll rename it and make a common signal factoring in kill and halt. I think the flag should be cleared if the instruction in WB is killed, as it should not increase any counters post mortem.

2021-09-29 11:18 UTC, silabs-halfdan approved these changes

2021-09-29 14:00 UTC, silabs-halfdan approved these changes

2021-09-29 14:10 UTC, Silabs-ArjanB requested changes

2021-09-29 14:10 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +        if(!ctrl_fsm_o.halt_wb) begin
This code is not intuitive to me. Would replacing this with if (!wb_ready_i) give the same result (as I think that code would be more intuitive). Specifically this is not clear because it does not explain how double counting is prevented for stalled loads/stores and it also makes fence.i a special case which I don't think is needed.

2021-09-30 07:42 UTC, Silabs-ArjanB approved these changes

2021-09-30 08:13 UTC, silabs-oysteink commented
Self merging after updating comments and aligning with Arjan.

2021-09-30 08:13 UTC, merged