Implement minimal CORE-V-XIF functionality
openhwgroup/cv32e40x pull request #272
Opened 2021-10-13 10:09 UTC by michael-platzer

This PR implements minimal functionality for the [CORE-V-XIF eXtension interface](https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/) by adding the required logic to the ID stage to drive the `issue` sub-interface, the FSM controller to drive the `commit` sub-interface, and the WB stage to receive results via the `result` sub-interface of the eXtension interface.

This minimal implementation is just enough to be usable at all for offloading instructions to a coprocessor and receiving results. It is neither complete nor error free. In particular, there are still following issues:

- Instruction IDs are not used, all instructions have ID 0.
- The controller commits all offloaded instructions regardless of any exceptions.
- Synchronous exceptions within the coprocessor indicated by the result interface are ignored (they only inhibit writeback of the result).
- Data hazards are ignored: If the result of an offloaded instruction is used by the subsequent instruction, then some random value is forwarded from the EX stage without waiting for the actual result (which only becomes available in the WB stage).

Despite these shortcomings, this implementation is already capable of offloading instructions to the [vector coprocessor Vicuna](https://github.com/vproc/vicuna/tree/cv32e40x-integration).

2021-10-13 12:33 UTC, michael-platzer commented
I just realized that the accept/reject by the coprocessor gets lost in case the ID stage is stalled by `ex_ready_i` being low. The second commit fixes this by remembering the accept/reject.

2021-10-13 13:09 UTC, silabs-oysteink requested changes

2021-10-13 13:25 UTC, michael-platzer commented on rtl/cv32e40x_id_stage.sv
> +
Thanks, I missed that, `issue_valid` should be de-asserted once the instruction has been accepted or rejected.

2021-10-13 16:02 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +  always_ff @(posedge clk, negedge rst_n) begin : ID_XIF_STATE_REGISTERS
Can you add a todo that we check whether this state machine should be put back in its initial state when the instruction in ID gets killed? (Normally all FSMs return to their initial state when a pipeline stage is killed)

2021-10-13 16:07 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +  assign xif_issue_if.x_issue_req.mode      = '0; // TODO: use the actual mode
The 40X only supports machine mode, so you can tie this to (a casted version of) PRIV_LVL_M.

2021-10-13 16:17 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +                       id_ex_pipe_i.xif_insn                ||
For consistency I would like it better if we use xif_en instead of xif_insn everywhere in the design (pretending that there is a functional unit called xif).

This line becomes: 

(id_ex_pipe_i.xif_en && xif_valid)

You can then also add:

// XIF is modeled as a functional unit that occupies EX for a single cycle no matter whether the result handshake is received in a single cycle or not.
  assign xif_valid = 1'b1;
  assign xif_ready = wb_ready_i;

and add xif_ready into the ex_ready_o expression.

All of this is equivalent to what you wrote; we just want it like that for consistency and ease of review.

2021-10-14 07:48 UTC, michael-platzer commented on rtl/cv32e40x_wb_stage.sv
> +  assign xif_result_if.x_result_ready = ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.xif_insn;
Yes, this makes sense. I have added a TODO in `cv32e40x_ex_stage.sv` and would add this in a further PR.

2021-10-14 07:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +  assign rf_re_o             = illegal_insn ? '1 : rf_re;
Agreed; we will think of a solution.

2021-10-14 07:54 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign xif_result_if.x_result_ready = ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.xif_insn;
Okay

2021-10-14 10:40 UTC, merged