Implemented write buffer (1/2)
openhwgroup/cv32e40x pull request #284
Opened 2021-10-15 12:32 UTC by halfdan-dolva

Implemented write buffer on transfer request signals.
Does not currently lead to any performance increase as we still wait for rvalid regardless of bufferable.
The change is logically equivalent when assumed 1 is set on data_gnt.

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-10-15 15:18 UTC, Silabs-ArjanB commented on rtl/cv32e40x_write_buffer.sv
> +  assign ready_o = (state == WBUF_EMPTY) && (bufferable || ready_i);
This does not look optimal to me. What would happen for example if there are two bufferable stores in a row and at the end of a first cycle the first store actually enters the write buffer (i.e. state becomes full) and in the second cycle the initial store receives its grant? I would expect that at the end of this second cycle the second bufferable store can enter the write buffer (but it would not).

2021-10-15 15:19 UTC, Silabs-ArjanB commented on sva/cv32e40x_write_buffer_sva.sv
> +    @(posedge clk)
Please always use disable iff (!rst_n) for all assertions

2021-10-15 15:24 UTC, Silabs-ArjanB commented on sva/cv32e40x_write_buffer_sva.sv
> +  ///////////////////////////////////////////
Do you expect that both interfaces of the write buffer are OBI compliant? If so, add assertions on both interfaces.

2021-10-15 15:27 UTC, Silabs-ArjanB commented on rtl/cv32e40x_write_buffer.sv
> +      WBUF_FULL: begin // buffer is full
I expect that you will need to allow for a FULL-> FULL transition

2021-10-15 15:27 UTC, Silabs-ArjanB commented on rtl/cv32e40x_write_buffer.sv
> +  assign ready_o = (state == WBUF_EMPTY) && (bufferable || ready_i);
I will re-look at the assertions after the design has been updated.

2021-10-18 14:09 UTC, silabs-hfegran requested changes

2021-10-18 14:11 UTC, silabs-hfegran commented on sva/cv32e40x_write_buffer_sva.sv
> +      ##1 (trans_q !== $past(trans_q)) |-> (state === WBUF_FULL) && ($past(bufferable) && ($past(state) === WBUF_EMPTY) && ($past(valid_i) && !$past(ready_i))); // ##1 used to avoid first clock edge
(same goes for the updated property, with minor modifications)

2021-10-18 14:12 UTC, Silabs-ArjanB commented on sva/cv32e40x_write_buffer_sva.sv
>        bufferable && !ready_o |-> (state === WBUF_FULL);
The right hand side can be made stronger

2021-10-18 14:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_write_buffer.sv
> +  assign ready_o = (state == WBUF_FULL) ? (bufferable && ready_i) : (bufferable || ready_i);
This deserves some comments

2021-10-18 14:45 UTC, silabs-halfdan commented on rtl/cv32e40x_write_buffer.sv
> +  assign ready_o = (state == WBUF_FULL) ? (bufferable && ready_i) : (bufferable || ready_i);
Will add some comments

2021-10-18 14:45 UTC, silabs-halfdan commented on rtl/cv32e40x_write_buffer.sv
> +      WBUF_FULL: begin // buffer is full
This arc is now added

2021-10-18 15:41 UTC, merged