move expected result to signals outside sva
openhwgroup/cv32e40x pull request #29
Opened 2021-04-19 07:04 UTC by silabs-robin

The expected result_o of the multiplier SVAs are moved to their own signals.
This makes it much easier to inspect failures in waveforms.

2021-04-19 07:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_mult_sva.sv
> +  logic [31:0] mul_result = $signed(op_a_i) * $signed(op_b_i);
Please split into separate declaration and assignment. Same remark for the other *result signals.

2021-04-19 07:54 UTC, Silabs-ArjanB requested changes
See comment

2021-04-26 08:12 UTC, silabs-robin commented on sva/cv32e40x_mult_sva.sv
> +  logic [31:0] mul_result = $signed(op_a_i) * $signed(op_b_i);
I have now split declarations from assignments.

2021-04-26 08:33 UTC, Silabs-ArjanB approved these changes

2021-04-26 08:33 UTC, merged