Updated pma-related assertions
openhwgroup/cv32e40x pull request #301
Opened 2021-11-02 14:44 UTC by silabs-hfegran

Updated pma-related assertions to account for unreachables and write buffer

Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>

2021-11-02 15:55 UTC, silabs-halfdan requested changes

2021-11-02 15:55 UTC, silabs-halfdan commented on sva/cv32e40x_mpu_sva.sv
> +      assert property (@(posedge clk) disable iff (!rst_n) bus_trans_bufferable |-> !load_access && pma_expected_cfg.bufferable)
Only regular store instructions can be bufferable (atomic instructions would trigger this assertion).

2021-11-02 15:55 UTC, silabs-halfdan commented on sva/cv32e40x_core_sva.sv
> +          else `uvm_error("core", "Atomic operation classified as bufferable")
Typo - classified as **non-**bufferable

2021-11-03 07:25 UTC, silabs-hfegran commented on sva/cv32e40x_mpu_sva.sv
> +      assert property (@(posedge clk) disable iff (!rst_n) bus_trans_bufferable |-> !load_access && pma_expected_cfg.bufferable)
Thanks - updated

2021-11-03 07:28 UTC, silabs-hfegran commented on sva/cv32e40x_core_sva.sv
> +          else `uvm_error("core", "Atomic operation classified as bufferable")
This is not a typo - it is in line with the other messages in this sva-file; i.e. not reporting what the assertion should do, but actually what (erroneously) happened.

2021-11-08 10:48 UTC, silabs-oivind approved these changes

2021-11-08 11:58 UTC, Silabs-ArjanB requested changes

2021-11-08 11:58 UTC, Silabs-ArjanB commented on sva/cv32e40x_core_sva.sv
> +                         !data_atop_o)
Replace !data_atop_o by data_atop_o != 6'b0 (don't use ! for multibit signals)

2021-11-08 11:58 UTC, Silabs-ArjanB commented on sva/cv32e40x_mpu_sva.sv
> +                         is_pma_matched |-> ((0 <= pma_match_num) && (pma_match_num <= 16)))
Should pma_match_num <= 16 be pma_match_num < 16?

2021-11-08 12:09 UTC, silabs-hfegran commented on sva/cv32e40x_core_sva.sv
> +                         !data_atop_o)
Thanks, updated code accordingly

2021-11-08 12:10 UTC, silabs-hfegran commented on sva/cv32e40x_mpu_sva.sv
> +                         is_pma_matched |-> ((0 <= pma_match_num) && (pma_match_num <= 16)))
Agreed, this should have been < 16

2021-11-08 12:14 UTC, Silabs-ArjanB approved these changes

2021-11-08 12:14 UTC, merged