Implemented response filter in lsu
openhwgroup/cv32e40x pull request #314
Opened 2021-11-12 15:31 UTC by silabs-halfdan

Implemented response filter in the load/store unit for performance improvements to bufferable writes.

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-11-15 08:25 UTC, silabs-oysteink requested changes

2021-11-15 08:25 UTC, silabs-oysteink commented on rtl/cv32e40x_lsu_response_filter.sv
> +  logic [DEPTH:0]        outstanding_bufferable_q;
Is the shift register deliberately DEPTH+1 bits?

2021-11-15 08:25 UTC, silabs-oysteink commented on rtl/cv32e40x_lsu_response_filter.sv
> +      outstanding_bufferable_next[1] = trans_i.memtype[0];
Index 0 seems unused, if on purpose it should be explained in a comment.

2021-11-15 08:42 UTC, Silabs-ArjanB requested changes
Just requesting some more comments and some signal renaming

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +     .bus_trans_valid_o    ( filter_trans_valid ),
Make sure prefixes matches signal in a better way. In particular now it is confusing that bus_resp_i comes from a different place than the other bus_* signals.

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +        lsu_addr_1_o <= bus_trans.addr;
Why are bus_trans* signals used together with trans* signals? Check maybe with Øystein as he had some todos here anyway.

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  assign lsu_err_1_o = bus_resp_valid && resp_err;
Here signals from different places in the design are combined. It fixes the bug Øivind found, but it should be explained why it is okay to combine these two signals with different prefixes.

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +// Design Name:    Write Buffer                                               //
Fix design name

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  assign busy_o = resp_filter_busy || trans_valid;
Can you add an assertion that cnt_q != 2'b00 implies resp_filter_busy?

2021-11-15 08:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  logic         resp_filter_busy;        // Response filter busy
Rename to filter_resp_busy

2021-11-15 08:44 UTC, Silabs-ArjanB requested changes
Also please add a subsection in the LSU section of the user manual explaining that there is one entry deep write buffer and explain which transactions can(not) get buffered.

2021-11-15 10:38 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +  assign resp_valid_o = (resp_is_bufferable) ? bufferable_resp_q && !non_bufferable_pending : resp_valid_i;
If resp_is_bufferable = 1, why does it matter at all what other transactions are in the FIFO? For example if the oldest transaction in the FIFO is bufferable and it is followed by a non-bufferable transaction in the FIFO, I would still expect that this oldest transaction gets its resp_valid_o = 1 immediately (no matter what else is in the FIFO). Of course there needs to be RTL that takes care that each transaction in the FIFO results in exactly 1 resp_valid_o = 1. I would expect two counters: One that points to the oldest transaction that still needs to receive an resp_valid_i and one that points to the oldest transaction for which resp_valid_o is being generated.

2021-11-16 10:14 UTC, silabs-halfdan commented on rtl/cv32e40x_lsu_response_filter.sv
> +  logic [DEPTH:0]        outstanding_bufferable_q;
Yes, will add comment.

2021-11-16 10:15 UTC, silabs-halfdan commented on rtl/cv32e40x_lsu_response_filter.sv
> +      outstanding_bufferable_next[1] = trans_i.memtype[0];
Correct, index 0 is unused, done to match cnt_q values directly. Will add comment.

2021-11-16 10:24 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +     .bus_trans_valid_o    ( filter_trans_valid ),
Will fix indentation and make explicit signal past the write buffer.

2021-11-16 10:27 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +        lsu_addr_1_o <= bus_trans.addr;
Good point, theses should not be mixed. Will discuss the todo w/ Øystein.

2021-11-16 10:30 UTC, silabs-halfdan commented on rtl/cv32e40x_lsu_response_filter.sv
> +// Design Name:    Write Buffer                                               //
Will do...

2021-11-16 10:31 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +  assign busy_o = resp_filter_busy || trans_valid;
Yes, that would be a good assertion. Will add.

2021-11-16 10:41 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +  logic         resp_filter_busy;        // Response filter busy
Yes, that's better.

2021-11-16 13:03 UTC, silabs-halfdan commented on rtl/cv32e40x_lsu_response_filter.sv
> +  assign resp_valid_o = (resp_is_bufferable) ? bufferable_resp_q && !non_bufferable_pending : resp_valid_i;
This is a good point. This is a limitation and it is not needed. Adding a counter on the core side of the response filter will (or use the already implemented lsu counter) will remove the limitation and make the code cleaner.
I will update the design and documentation to use two counters instead of generating a response pulse.

2021-11-16 14:41 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +  assign lsu_err_1_o = bus_resp_valid && resp_err;
It's only ok because the resp_err signal is unchanged by the mpu, so there is no good reason to mix prefixes here.
Will change it to use bus_resp_err instead.

2021-11-18 07:15 UTC, Silabs-ArjanB approved these changes

2021-11-18 07:28 UTC, Silabs-ArjanB approved these changes

2021-11-18 07:29 UTC, merged