Added check CSR instruction accepted by xif AND pipeline.
openhwgroup/cv32e40x pull request #316
Opened 2021-11-16 11:45 UTC by silabs-oysteink

Killing xif instruction via commit interface in EX, and marking instruction
as illegal.

Note that the commit_kill signal is not fully implemented yet. It will get updated in a future PR with proper killing for interrupts, debug and exceptions. Changes are expected to the way commit_kill is signalled, as for killed instructions ex_valid will not be 1.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-11-16 14:22 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !((id_ex_pipe_i.instr.mpu_status != MPU_OK) || (id_ex_pipe_i.instr.bus_resp.err))
Can you add a todo here? The '!((id_ex_pipe_i.instr.mpu_status != MPU_OK) || (id_ex_pipe_i.instr.bus_resp.err))' part should not be needed once instruction offload is implemented according to spec (forbidding offload exactly for these conditions and more)

2021-11-16 14:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +        ex_wb_pipe_o.illegal_insn   <= id_ex_pipe_i.illegal_insn || csr_illegal_i || xif_csr_error_o;
I think all (or at least most) uses of csr_illegal_i are now not correct. Consider the case where a CSR instruction is offloaded and accepted by a coprocessor and leads to csr_illegal_i in the core. In that case no illegal_insn should be caused. So basically you get an illegal instruction here if neither the coproc nor the processor accepts the CSR instruction or if both accept it. If exactly one of them accepts it, then there is no issue.

2021-11-16 14:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +  assign xif_csr_error_o = id_ex_pipe_i.xif_en && (id_ex_pipe_i.csr_en && !csr_illegal_i);
I am always a bit paranoid when instr_valid is not used. Can you explain why that signal is not needed here?

2021-11-16 14:30 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !((id_ex_pipe_i.instr.mpu_status != MPU_OK) || (id_ex_pipe_i.instr.bus_resp.err))
Good point, I'll add a todo.

2021-11-16 14:30 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +        ex_wb_pipe_o.illegal_insn   <= id_ex_pipe_i.illegal_insn || csr_illegal_i || xif_csr_error_o;
You're right, this need to change.

2021-11-17 14:33 UTC, Silabs-ArjanB requested changes

2021-11-17 14:33 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +        // to avoid writing to CSRs inside the core.
On the next line I think that csr_en needs to be suppressed based on csr_is_illegal as well

2021-11-17 14:33 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +  // in case of halt_ex==1. We need to kill this duplicate regardless of halt state.
I had specified that we would kill or commit offloaded instruction specifically only when halt_ex = 0. Are you saying that there are scenarios where we cannot wait for that to happen?

2021-11-17 14:48 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +        // to avoid writing to CSRs inside the core.
An offloaded CSR instruction that is also accepted by the core (csr_illegal_i = 0) will cause csr_is_illegal to be 1. But if an offloaded CSR also causes an illegal CSR in the pipeline, csr_is_illegal would be 0, as only the XIF accepted the instruction. Thus we need to deassert csr_en by using the csr_illegal_i from cs_registers, otherwise we may end up writing random values to CSRs when the XIF should be the only one handling CSR instructions. This case is shown in formal where DCSR may be written from machine mode, unless we suppress csr_en based on csr_illegal_i.

2021-11-17 16:02 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +        // to avoid writing to CSRs inside the core.
>> Thus we need to deassert csr_en by using the csr_illegal_i from cs_registers, otherwise we may end up writing random values to CSRs when the XIF should be the only one handling CSR instructions.

That is true, but there are 4 cases and not all of them are handled correctly yet:

1. CSR accepted by XIF && CSR legal in core -> ex_wb_pipe_o.csr_en does need to become suppressed to 0 (not handled in current code)
2. CSR not accepted by XIF && CSR legal in core -> ex_wb_pipe_o.csr_en does not need to be suppressed
3. CSR accepted by XIF && CSR not legal in core -> ex_wb_pipe_o.csr_en does need to become suppressed to 0 (handled in current code)
4. CSR not accepted by XIF && CSR not legal in core -> ex_wb_pipe_o.csr_en does need to become suppressed to 0 (handled in current code)

2021-11-18 08:08 UTC, Silabs-ArjanB approved these changes

2021-11-18 08:08 UTC, merged