Expand rvfi_trap to provide more information about trap type and cause
openhwgroup/cv32e40x pull request #322
Opened 2021-11-18 13:11 UTC by silabs-oivind

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

2021-11-18 15:54 UTC, Silabs-ArjanB requested changes

2021-11-18 15:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_rvfi_sva.sv
> +                    (no_debug && !instr_err_i && !ctrl_fsm_i.pending_nmi) throughout s_goto_next_rvfi_valid(|rvfi_trap) |->
Can you explain why instruction bus error and NMI are excluded here?

2021-11-19 08:47 UTC, silabs-oysteink approved these changes

2021-11-19 09:45 UTC, silabs-oivind commented on sva/cv32e40x_rvfi_sva.sv
> +                    (no_debug && !instr_err_i && !ctrl_fsm_i.pending_nmi) throughout s_goto_next_rvfi_valid(|rvfi_trap) |->
Updated comment. Instruction bus error does not need to be excluded here.

2021-11-19 09:50 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +   input logic                                pending_single_step_i,
Cleaned up, using ctrl_fsm_i where possible with current ctrl_fsm_t. 
I'm hesitant to add signals internal to the FSM to ctrl_fsm_t, mostly because it'll add noise when viewing ctrl_fsm in waveform viewer.

2021-11-19 10:48 UTC, Silabs-ArjanB approved these changes

2021-11-19 10:48 UTC, merged