Silabs oysteink xif commit kill
openhwgroup/cv32e40x pull request #326
Opened 2021-11-23 13:10 UTC by silabs-oysteink

2021-11-23 14:08 UTC, Silabs-ArjanB requested changes

2021-11-23 14:08 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_ready_o = !xif_waiting; // signal ready to LSU only if there is no waiting offloaded instruction
Why is this and why should or should this not depend on the loadstore signal?

2021-11-23 14:08 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +} xif_meta_t;
Add accept signal

2021-11-24 13:51 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +                                                 (id_ex_pipe_i.xif_en && id_ex_pipe_i.instr_valid) &&
Fixed

2021-11-24 13:54 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +} xif_meta_t;
Done

2021-11-24 15:02 UTC, Silabs-ArjanB requested changes
Can you just add a todo for the issue I spotted in the ID stage. I still did not spend time on reviewing the assertions. I think we will end up rewriting most of the XIF code to introduce a scoreboard and allow some out of order completion. The assertions will change then again anyway, so we can look at them later.

2021-11-24 15:50 UTC, Silabs-ArjanB approved these changes

2021-11-24 15:50 UTC, merged