Instantiate PMA on data bus
openhwgroup/cv32e40x pull request #34
Opened 2021-04-22 14:35 UTC by silabs-oivind

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

PMA is instantiated, but controller is not updated yet.
SEC clean vs 39aeb6c

2021-04-22 15:30 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +
Can above names be made similar? Either rename core_trans -> trans, core_resp -> resp, or the other way around prefix all signals with core_?

2021-04-22 15:34 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mpu.sv
> +      type(obi_inst_req_t): begin
All generate scopes need names

2021-04-22 15:35 UTC, Silabs-ArjanB requested changes
I left some minor feedback; can you address those items?

2021-04-23 06:58 UTC, silabs-oivind commented on rtl/cv32e40x_load_store_unit.sv
> +
Removed core_ prefix.

2021-04-23 06:58 UTC, silabs-oivind commented on rtl/cv32e40x_mpu.sv
> +      type(obi_inst_req_t): begin
Labels added.

2021-04-23 07:22 UTC, Silabs-ArjanB approved these changes

2021-04-23 07:22 UTC, merged