Fix for issue #343
openhwgroup/cv32e40x pull request #352
Opened 2021-12-15 13:17 UTC by silabs-oysteink

LSU response filter is now outputting what type of load/store is associated with a bus error.
Also routing the bus_resp through the filter for cleaner code.
Controller now gets two bits from the load_store_unit, one for qualifying an NMI and one for
signaling if it is for a load or store.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2021-12-15 15:04 UTC, silabs-halfdan approved these changes

2021-12-16 07:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  assign lsu_err_1_o = filter_bus_error;
Rename filter_bus_error to filter_err (matching closer to lsu_err_1_o and avoiding bus in the name to more clearly state the origin of the signal)

2021-12-16 07:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +       .bus_error_o  ( filter_bus_error   )
.err_o ( filter_err), (and move this to line 383 (the 'filter' side signals)

2021-12-16 07:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +   output obi_data_resp_t resp_o,
You can also make this a todo

2021-12-16 07:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +      outstanding_bufferable_next[DEPTH:1]    = outstanding_bufferable_q[DEPTH-1:0];
Agreed (best to make it explicit and tie these bits low here as well)

2021-12-16 08:22 UTC, silabs-oysteink commented on rtl/cv32e40x_lsu_response_filter.sv
> +      outstanding_bufferable_next[DEPTH:1]    = outstanding_bufferable_q[DEPTH-1:0];
Done

2021-12-16 08:22 UTC, silabs-oysteink commented on rtl/cv32e40x_lsu_response_filter.sv
> +  resp_type_t [DEPTH:0]        outstanding_bufferable_q; // Using 1-DEPTH entries for outstanding xfers, index 0 is tied low
Done

2021-12-16 08:35 UTC, Silabs-ArjanB requested changes

2021-12-16 08:35 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +  assign bus_error_o[0] = resp_valid_i && resp_i.err;
Just a note: Maybe the qualification with resp_valid_i will move to the MPU later

2021-12-16 08:35 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                      |=> (nmi_is_store_q == bus_error_is_write))
Can the following be added to the antecedent?

&& (nmi_pending_q == bus_error_latched) && (bus_error_latched == 1)

2021-12-16 08:55 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                      |=> (nmi_is_store_q == bus_error_is_write))
Done

2021-12-16 10:57 UTC, Silabs-ArjanB approved these changes

2021-12-16 10:57 UTC, merged