RVFI updates to support privilege spec 1.12 CSR
openhwgroup/cv32e40x pull request #396
Opened 2022-01-17 12:49 UTC by silabs-hfegran

Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>

2022-01-17 13:57 UTC, Silabs-ArjanB requested changes

2022-01-17 13:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   input logic [31:0]                         csr_mstatush_i,
Every CSR should have an _n_i, _q_i and _we_i signal

2022-01-17 13:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   input logic [31:0]                         csr_mconfigptr_i,
Every CSR should have an _n_i, _q_i and _we_i signal

2022-01-17 13:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +   output logic [31:0]                        rvfi_csr_tcontrol_rmask,
Every CSR should have an _n_i, _q_i and _we_i signal

2022-01-17 13:57 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_wdata_d.mstatush           = '0;
These type of tie-offs should not be done inside the RVFI. Ideally these signals come from the core; if they don't exist there yet (and it is not easy to add), then these can be tied off where RVFI is being instantiated.

2022-01-17 14:02 UTC, silabs-halfdan requested changes

2022-01-17 14:31 UTC, silabs-hfegran commented
Thanks for your comments @silabs-halfdan and @Silabs-ArjanB, I will add those - I will make the necessary changes. 

As for the _we _n and _q signals, there are some CSRs that don't have this that I did not touch with these changes (mvendorid, march, mhartid) - should they also be changed?

2022-01-18 08:07 UTC, silabs-hfegran commented
I am still making some updates - will let you know when this is ready for review again

2022-01-20 14:38 UTC, Silabs-ArjanB commented
Hi @silabs-hfegran Is this one ready for review now?

2022-01-20 15:27 UTC, silabs-hfegran commented
> Hi @silabs-hfegran Is this one ready for review now?

Not yet, I will convert it to a proper PR (and not a draft as it currently is) when that is the case.  I am trying to synchronize the changes to the rvfi, the verification environment and the riscv-dv before getting everything in

2022-01-25 11:11 UTC, silabs-robin commented
What will break if this is merged before dv and cvverif?
(I am trying to see how these parts are connected.)

2022-01-25 11:17 UTC, silabs-hfegran commented
> What will break if this is merged before dv and cvverif? (I am trying to see how these parts are connected.)

compilation failure, due to missing registers

2022-01-31 07:31 UTC, silabs-hfegran commented
> What will break if this is merged before dv and cvverif? (I am trying to see how these parts are connected.)

These changes have not been tested stand-alone without the environment updates - I will do some testing and see if this can be done to speed up the integration process.

2022-02-09 10:57 UTC, silabs-halfdan approved these changes

2022-02-09 11:39 UTC, Silabs-ArjanB requested changes

2022-02-09 11:39 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_wmask_d.tcontrol           = csr_tcontrol_we_i ? '1 : '0;
Please do not tie off mcontext inside this module; it should come ideally the RTL or at least from input pins of this module.

2022-02-09 11:39 UTC, Silabs-ArjanB commented on bhv/cv32e40x_wrapper.sv
> +         .csr_mstatush_n_i         ( '0                                                                   ),
Add todo's to tie this to the RTL

2022-02-09 12:44 UTC, silabs-hfegran commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_wmask_d.tcontrol           = csr_tcontrol_we_i ? '1 : '0;
I'll add a TODO for design to fix, as mcontext-related code unchanged by this PR.

2022-02-09 13:56 UTC, Silabs-ArjanB approved these changes

2022-02-09 13:56 UTC, merged