Add M_EXT parameter
openhwgroup/cv32e40x pull request #401
Opened 2022-01-20 15:07 UTC by silabs-oivind

Add M_EXT parameter.
Update MISA to take M_EXT, X_EXT, X_MISA into account

2022-01-20 15:47 UTC, Silabs-ArjanB requested changes
Apart from the required decoder fixes we also need generate statements around multi_i and div_i.

2022-01-20 15:47 UTC, Silabs-ArjanB commented on rtl/cv32e40x_m_decoder.sv
> +            if (M_EXT == M) begin
All of these need an 'else' branch to cause an illegal instruction. I prefer if you would simply set the following in that branch:

decoder_ctrl_o = DECODER_CTRL_ILLEGAL_INSN;

2022-01-21 07:44 UTC, silabs-oivind commented on rtl/cv32e40x_m_decoder.sv
> +            if (M_EXT == M) begin
Yes, of course.. Added.

2022-01-21 07:46 UTC, silabs-oivind commented
> Apart from the required decoder fixes we also need generate statements around multi_i and div_i.

Added generate statements. Synth tools should be able to optimize away these instances without the generate statement because their outputs are static/not used. But agree it's cleaner to add generate statements.

2022-01-21 07:58 UTC, Silabs-ArjanB approved these changes

2022-01-21 07:58 UTC, merged