Remove logic from top level
openhwgroup/cv32e40x pull request #42
Opened 2021-04-30 07:56 UTC by silabs-oivind

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

SEC clean

2021-04-30 09:54 UTC, Silabs-ArjanB requested changes

2021-04-30 09:54 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
>      .csr_access_i               ( id_ex_pipe.csr_access  ),
Now that id_ex_pipe is fed into the CSR file, this signal should be removed from the interface.

2021-05-03 08:41 UTC, silabs-oivind commented on rtl/cv32e40x_core.sv
>      .csr_access_i               ( id_ex_pipe.csr_access  ),
Updated.

2021-05-03 10:31 UTC, Silabs-ArjanB approved these changes

2021-05-03 10:31 UTC, merged