Added CLIC and Zc* CSRs and doc
openhwgroup/cv32e40x pull request #420
Opened 2022-02-07 13:49 UTC by silabs-halfdan

Added CLIC and Zc* CSRs and related documentation.

2022-02-07 16:19 UTC, Silabs-ArjanB requested changes

2022-02-07 16:19 UTC, Silabs-ArjanB commented on docs/user_manual/source/control_status_registers.rst
> +This register holds the active machine mode interrupt level threshold.
Remove 'active'

2022-02-07 16:19 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +  parameter bit          SMCLIC                       = 0,
Also add in wrapper and connect in its core instance

2022-02-07 16:19 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      assign mscratchcsw_q  = 32'h0;
Why can't you just instantiate these three CSRs?

2022-02-08 09:28 UTC, silabs-halfdan commented on docs/user_manual/source/control_status_registers.rst
> +.. only:: ZC
will merge into main table

2022-02-08 09:32 UTC, silabs-halfdan commented on docs/user_manual/source/control_status_registers.rst
> +| 31 : 6      |   RW       | **Address**: Trap-handler vector table base address, 64 byte aligned. |
Will update it

2022-02-08 09:35 UTC, silabs-halfdan commented on rtl/cv32e40x_core.sv
> +  parameter bit          SMCLIC                       = 0,
Will add

2022-02-08 09:37 UTC, silabs-halfdan commented on rtl/cv32e40x_cs_registers.sv
> +      assign mscratchcsw_q  = 32'h0;
Expecting the implementation of these to not be straight forward registers, but will add them for now.

2022-02-08 09:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      assign mscratchcsw_q  = 32'h0;
Just add todo's on the parts that you know are not ready yet

2022-02-08 11:07 UTC, Silabs-ArjanB approved these changes

2022-02-08 11:07 UTC, merged