Finalized core interface
openhwgroup/cv32e40x pull request #429
Opened 2022-02-11 11:33 UTC by silabs-halfdan

Finalized core interface signals and parameters, in rtl and doc.

2022-02-11 13:03 UTC, Silabs-ArjanB requested changes

2022-02-11 13:03 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  assign align_trans.dbg     = ctrl_fsm_i.debug_mode;
Feed the debug signal all the way from 'trans' instead.

2022-02-14 09:46 UTC, silabs-halfdan commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.debug_mode_if = debug_mode_n;
Added comment with reasoning for _if signal.

2022-02-14 09:48 UTC, silabs-halfdan commented on rtl/cv32e40x_load_store_unit.sv
> +  assign align_trans.dbg     = ctrl_fsm_i.debug_mode;
Added dbg to the trans_req_t struct and fed dbg from trans.

2022-02-14 13:14 UTC, Silabs-ArjanB requested changes

2022-02-14 13:14 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  typedef enum logic {RV32I, RV32E} rv32_base_integer_instr_set_e;
Rename enumeration to rv32_e and use everywhere (including wrapper) where RV32 parameter is used.

2022-02-14 13:54 UTC, silabs-halfdan commented on rtl/include/cv32e40x_pkg.sv
> +  typedef enum logic {RV32I, RV32E} rv32_base_integer_instr_set_e;
Renamed it now

2022-02-14 14:12 UTC, Silabs-ArjanB approved these changes

2022-02-14 14:12 UTC, merged