RVFI Sleep Signals
openhwgroup/cv32e40x pull request #487
Opened 2022-03-24 13:25 UTC by silabs-halfdan

Added rvfi_wu and rvfi_sleep signals to rvfi, fixed issue with rvfi_csr_mip_rdata signal

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2022-03-24 14:03 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_rdata_d.mip                = csr_en_wb_i ? ex_csr_rdata.mip : csr_mip_q_i;
Please add a comment on 'why' this was done

2022-03-24 14:20 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_sleep     <= (ctrl_fsm_ns_i == SLEEP);
Good point, WFIs will not enter sleep if there are flopped wakeup causes. This code will signal a sleep and wakeup event if the wakeup cause is set in the same cycle as the WFI retires, although the core_sleep_o signal will never be set.
I can update it to also consider the un-flopped wakeup signals.

2022-03-24 14:20 UTC, silabs-halfdan commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_rdata_d.mip                = csr_en_wb_i ? ex_csr_rdata.mip : csr_mip_q_i;
Will add a comment

2022-03-24 14:28 UTC, Silabs-ArjanB requested changes

2022-03-24 14:28 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  assign rvfi_csr_rdata_d.mip                = csr_en_wb_i ? ex_csr_rdata.mip : csr_mip_q_i;
Is this also correct for WFI instructions, which take (at least) 2 cycles in WB and for which I believe they are reported on RVFI during their first WB cycle (so not necessarily with the correct MIP I think)

2022-03-29 06:01 UTC, Silabs-ArjanB approved these changes

2022-03-29 06:01 UTC, merged