Basic CLIC vectoring support
openhwgroup/cv32e40x pull request #492
Opened 2022-03-29 13:51 UTC by silabs-oysteink

Work-in-progress, do not merge.

Basic CLIC controller (without thresholds) is included.
- For CLIC, vectoring is implemented through the alignment buffer.
Core should still work in basic mode.

2022-03-29 14:03 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alignment_buffer.sv
> +  // CLIC vectoring or Zce table jump
Zce -> Zc

2022-03-29 14:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_clic_int_controller.sv
> +      clic_irq_q     <= 1'b0;
Remove repeated spaces before <=

2022-03-29 14:21 UTC, Silabs-ArjanB commented on rtl/cv32e40x_clic_int_controller.sv
> +        clic_irq_shv_q   <= clic_irq_shv_i;
level, priv, shv not used yet.
Actually priv will always be M mode (also for 40S); add assertion to check this and also add comment that this will be the case. Maybe change reset value of priv_q to machine mode so that this will surely get optimized away

2022-03-29 14:27 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.m_exc_vec_pc_mux = (mtvec_mode_i == 2'b0) ? 11'h0 : exc_cause;
I think it will be cleaner to have a separate mtvec_pc_mux and mtvt_pc_mux

2022-03-29 14:28 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  // todo: CLIC, faulted vector loads (from the IF stage) must be treated as EXC_CAUSE_LOAD_FAULT
Can that already be done in the MPU?

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +    ctrl_fsm_o.pc_set_clicv = 1'b0;
Not aligned to previous line

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
>            ctrl_fsm_o.irq_id  = irq_id_ctrl_i;
Width of irq_id, irq_id_ctrl_i should be updated to deal with 1024 interrupts.

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
>            exc_cause = irq_id_ctrl_i;
Width mismatch

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +      // State for CLIC vectoring (and Zce table jumps)
Zce -> Zc

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +        if(if_id_pipe_i.instr_meta.clicv) begin
if( -> if (

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +        if(if_id_pipe_i.instr_meta.clicv) begin
Shouldn't this be qualified with some valid signal? Also add comment on how associated errors (e.g. bus error) will be handled.

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +          ctrl_fsm_o.kill_id = 1'b1; // No need to let this psuedo op continue todo: pass on to WB if exception
Why not always pass it on? Also describe if there can for example be a instruction address breakpoint associated with this or not.

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
>    assign irq_id  = ctrl_fsm.irq_id;
Width mismatch

2022-04-01 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +      int_controller_i
int_controller_i -> clic_int_controller_i

2022-04-01 11:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +        if_id_pipe_o.instr            <= prefetch_is_ptr ? prefetch_instr : instr_decompressed;
This mux already exists inside the comrpessed decoder. Remove it here and adapt the compressed decoder instead. Also make sure inside that decoder that is_compressed_o = 0 for pointers.

2022-04-01 11:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_prefetcher.sv
> +
Zce -> Zc
Transaction is treated as a data access (1 for CLIC, 0 for Zc)

2022-04-01 11:14 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +typedef enum logic [2:0] { RESET, BOOT_SET, FUNCTIONAL, SLEEP, DEBUG_TAKEN, VECTORING} ctrl_state_e;
VECTORING -> POINTER_FETCH

2022-04-01 11:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_prefetcher.sv
> +  assign trans_data_access_o = fetch_data_access_i;
I think that this assignment is the reason why the pointer fetch control is a bit awkward. trans_data_access_o assignments should be handled in a similar manner as the trans_addr_o assignments. Put an assign to this signal whereever there is an assign to trans_addr_o to make this easier to review.

2022-04-01 11:27 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  PC_TRAP_CLICV = 4'b1101,
Will this get extended with more value when implementing table jump; if so, how? (I might want to rename these, but it depends on how table jump will be handled)

2022-04-01 11:27 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  logic        clicv;
Similar, what will this look like after adding table jump?

2022-04-01 11:27 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  logic [10:0] irq_id;                // id of taken irq. Max width, unused bits will be tied off
There will be max 1024 interrupts, why 11 bits? If it is due to NMIs, why did 5 bits suffice before?

2022-04-01 11:27 UTC, Silabs-ArjanB commented on sva/cv32e40x_alignment_buffer_sva.sv
> +  endproperty
Nice!

2022-04-01 11:27 UTC, Silabs-ArjanB commented on sva/cv32e40x_alignment_buffer_sva.sv
> +    else
Zce -> Zc

2022-04-01 11:27 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +  // todo: CLIC: Vector loads must respect mprv
prot[0] assignment needs to be updated. 
Add assertion that no back-to-back data (pointer) fetches can occur on instruction OBI.

2022-04-01 13:01 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alignment_buffer.sv
> +  output logic [31:0]    instr_addr_o,
Add assertion that the address from where the pointer was fetched is word-aligned.

2022-04-04 19:09 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +        is_ptr_q <= ctrl_fsm_i.pc_set_clicv;
Yes, I believe that one can be shared.

2022-04-04 19:13 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_valid_o = (ctrl_fsm_i.instr_req || !ptr_fetch_done_q) &&
Agreed, it makes the code a little less clean. One alternative would be to let the controller know the state of fetches being accepted or not, but I'm not sure if that is any cleaner.

2022-04-04 19:14 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +      ptr_fetch_done_q  <= 1'b1; // Reset to 1 to avoid pointer fetches out of reset
Comment added. We could of course flip the polarity of the bit, so it would become "ptr_fetch_pending_q" instead, causing a better reset value of 0.

2022-04-04 19:14 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  // CLIC vectoring or Zce table jump
Fixed

2022-04-04 19:15 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_data_access_o = ctrl_fsm_i.pc_set_clicv || (is_ptr_q && !(ctrl_fsm_i.pc_set && !ctrl_fsm_i.pc_set_clicv));
pc_set is implied, but for clarity we should add it anyway.

2022-04-04 19:15 UTC, silabs-oysteink commented on rtl/cv32e40x_clic_int_controller.sv
> +      clic_irq_q     <= 1'b0;
Fixed

2022-04-04 19:30 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  // todo: CLIC, faulted vector loads (from the IF stage) must be treated as EXC_CAUSE_LOAD_FAULT
The MPU would need some more state, so I think it is cleaner to to do it in the controller.

2022-04-04 19:31 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +    ctrl_fsm_o.pc_set_clicv = 1'b0;
Fixed

2022-04-04 19:33 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +      // State for CLIC vectoring (and Zce table jumps)
Fixed

2022-04-04 19:33 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +        if(if_id_pipe_i.instr_meta.clicv) begin
Fixed

2022-04-04 19:33 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +        if(if_id_pipe_i.instr_meta.clicv) begin
Fixed

2022-04-04 19:35 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +      int_controller_i
Fixed

2022-04-04 19:37 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +            ctrl_fsm_ns = VECTORING;
Agreed. Renamed to PTR_FETCH.

2022-04-04 19:38 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      assign mtvt_addr_o = mtvt_q.addr[31:(32-MTVT_ADDR_WIDTH)];
Done

2022-04-04 19:40 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +typedef enum logic [2:0] { RESET, BOOT_SET, FUNCTIONAL, SLEEP, DEBUG_TAKEN, VECTORING} ctrl_state_e;
Fixed

2022-04-04 19:42 UTC, silabs-oysteink commented on sva/cv32e40x_alignment_buffer_sva.sv
> +    else
Fixed

2022-04-05 06:14 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +      PC_TRAP_CLICV_TGT: branch_addr_n = if_id_pipe_o.instr.bus_resp.rdata;
Fixed

2022-04-05 06:19 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    .if_data_access_i     ( prefetch_trans_data_access  ), // Indicate data access from IF stage. TODO: Use for table jumps (?)
Fixed

2022-04-05 06:34 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_valid_o = (ctrl_fsm_i.instr_req || !ptr_fetch_done_q) &&
I expect that it will be cleanest if the controller simply does not lower instr_req for the pointer fetch scenario. I expect that can be a local decision inside the alignment buffer.

2022-04-05 06:36 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  // todo: CLIC, faulted vector loads (from the IF stage) must be treated as EXC_CAUSE_LOAD_FAULT
Agreed

2022-04-05 06:38 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_valid_o = (ctrl_fsm_i.instr_req || !ptr_fetch_done_q) &&
Agreed, I'll implement that.

2022-04-05 06:39 UTC, silabs-oysteink commented on rtl/cv32e40x_prefetcher.sv
> +
Fixed

2022-04-05 10:01 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
>            ctrl_fsm_o.irq_id  = irq_id_ctrl_i;
Fixed

2022-04-05 10:01 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +          ctrl_fsm_o.kill_id = 1'b1; // No need to let this psuedo op continue todo: pass on to WB if exception
Now always passed on

2022-04-05 10:02 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
>    assign irq_id  = ctrl_fsm.irq_id;
Fixed

2022-04-05 10:02 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +        if_id_pipe_o.instr            <= prefetch_is_ptr ? prefetch_instr : instr_decompressed;
Done

2022-04-05 10:03 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  PC_TRAP_CLICV = 4'b1101,
Yes, I think we need another entry to keep the code clean, as the table jumps will reference the jvt CSR instead of the mtvt. PC_TRAP_TBLJMP with a TBD value.

2022-04-05 10:04 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic        clicv;
I guess we need a separate bit since they are treated differently with respect to exceptions. 'tbljmp' could be a candiate name.

2022-04-05 10:04 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic [10:0] irq_id;                // id of taken irq. Max width, unused bits will be tied off
Wops, fixed.

2022-04-05 10:07 UTC, silabs-oysteink commented on sva/cv32e40x_rvfi_sva.sv
> +  /* todo: adapt to CLIC
I think we need to fix/adapt RVFI. I will look into it, it shouldn't be too much work.

2022-04-05 11:18 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +      ptr_fetch_done_q  <= 1'b1; // Reset to 1 to avoid pointer fetches out of reset
Fixed/restructured code.

2022-04-05 11:18 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_valid_o = (ctrl_fsm_i.instr_req || !ptr_fetch_done_q) &&
Fixed/restructured.

2022-04-05 11:19 UTC, silabs-oysteink commented on rtl/cv32e40x_clic_int_controller.sv
> +        clic_irq_shv_q   <= clic_irq_shv_i;
Now resetting to machine mode. The assertion would probably better be placed outside of the core, as the core external part of CLIC is driving this signal.

2022-04-05 11:21 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    instr_meta_n.clicv      = prefetch_is_ptr;
I think it will be cleaner if we have two different flags, 'clic_ptr' and 'tbljmp_ptr' for instance? They will likely be treated a bit different when it comes to exceptions.

2022-04-05 11:21 UTC, silabs-oysteink commented on rtl/cv32e40x_prefetcher.sv
> +  assign trans_data_access_o = fetch_data_access_i;
Done

2022-04-05 12:49 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +    instr_meta_n.clicv      = prefetch_is_ptr;
sounds good

2022-04-05 12:52 UTC, silabs-oysteink commented on sva/cv32e40x_decoder_sva.sv
> +  //a_uncompressed_lsb: assert property(p_uncompressed_lsb) else `uvm_error("decoder", "2 LSBs not 2'b11")
Done

2022-04-05 12:53 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +        ptr_fetch_done_q <= 1'b1;
Semantics changed, should be more intuitive now.

2022-04-05 12:53 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_data_access_o = ctrl_fsm_i.pc_set_clicv || (is_ptr_q && !(ctrl_fsm_i.pc_set && !ctrl_fsm_i.pc_set_clicv));
Moved to prefetcher

2022-04-05 12:54 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  assign fetch_valid_o = (ctrl_fsm_i.instr_req || !ptr_fetch_done_q) &&
Fixed

2022-04-05 12:55 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +  output logic [31:0]    instr_addr_o,
This already exists in the prefetcher_sva (p_fetch_branch_addr_aligned)

2022-04-05 13:00 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    instr_meta_n.clicv      = prefetch_is_ptr;
Renamed to meta.clic_ptr

2022-04-05 15:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +            mcause_n.mpil = mintstatus_q.mil;
This needs an explanation on why this works if SMCLIC = 0. Even better would be to explicitly set it to 0 in that case.

Maybe best to guard all CLIC related assignments in this file with SMCLIC and use 0 assignments if SMCLIC = 0.

2022-04-05 15:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +            mintstatus_n.mil = ctrl_fsm_i.irq_level;
This register does not exist when SMCLIC = 0 I would prefer if we can exclude such assignments (also following line) if SMCLIC = 0.

2022-04-05 15:25 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +        mcause_n = mcause_q;
Guard all content in this block. Should not get triggered if SMCLIC = 0.

2022-04-05 16:08 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +        // Bypass comressed decoder when result is a pointer
Update comment (pointer is passed on via compressed decoder)

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mtvec_pc_mux = ((mtvec_mode_i == 2'b0) || (mtvec_mode_i == 2'b11 && !irq_clic_shv_i)) ? 5'h0 : exc_cause[4:0];
brakets around the == comparison

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +                            !ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err   ||
brackets

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign exception_cause_wb = !ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.mpu_status != MPU_OK   ? EXC_CAUSE_INSTR_FAULT     :
Brackets around expressions used in select parts

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign pending_nmi = (nmi_pending_q || ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err) &&
Brackets

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign pending_nmi = (nmi_pending_q || ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err) &&
It seems you are not explicitly using nmi_pending_q and nmi_is_store_q. How will this NMI be treated correctly on rvfi_nmip?

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +          if(!((if_id_pipe_i.instr.mpu_status != MPU_OK) || if_id_pipe_i.instr.bus_resp.err)) begin
Add todo to deal with integrity related faults for 40S

2022-04-06 06:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +          ctrl_fsm_ns = FUNCTIONAL;
I think there might be a bug here. What happens if a ptr is in EX or WB and it is killed by an interrupt. What will the mepc be and what will happen upon re-execution from that mepc (will the ptr access be retried as an instruction fetch?). If this goes wrong (which I would expect) maybe the easiest solution is to disallow interrupts when there is a ptr in EX or WB. Additional question: What type of instruction can be in WB when there is a ptr in EX?

2022-04-06 06:57 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +            mcause_n.mpil = mintstatus_q.mil;
Fixed

2022-04-06 06:58 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +            mintstatus_n.mil = ctrl_fsm_i.irq_level;
Fixed

2022-04-06 06:58 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +        mintstatus_n.mil = mcause_q.mpil;
Fixed

2022-04-06 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +        mcause_n = mcause_q;
Fixed

2022-04-06 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_clic_int_controller.sv
> +                          clic_irq_level_q > effective_irq_level &&
Fixed

2022-04-06 07:03 UTC, silabs-oysteink commented on rtl/cv32e40x_clic_int_controller.sv
> +  // There a pending-and-enabled interrupt and interrupts are enabled globally
Fixed

2022-04-06 07:03 UTC, silabs-oysteink commented on rtl/cv32e40x_clic_int_controller.sv
> +  // AND the incoming irq level is above the cores current effective interrupt level.
Fixed

2022-04-06 07:05 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +        // Bypass comressed decoder when result is a pointer
Fixed

2022-04-06 07:07 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mtvec_pc_mux = ((mtvec_mode_i == 2'b0) || (mtvec_mode_i == 2'b11 && !irq_clic_shv_i)) ? 5'h0 : exc_cause[4:0];
Fixed

2022-04-06 07:08 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +                            !ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err   ||
Fixed

2022-04-06 07:09 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign exception_cause_wb = !ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.mpu_status != MPU_OK   ? EXC_CAUSE_INSTR_FAULT     :
Fixed

2022-04-06 07:20 UTC, Silabs-ArjanB requested changes

2022-04-06 07:20 UTC, Silabs-ArjanB commented on rtl/cv32e40x_prefetcher.sv
> +        trans_data_access_o = fetch_branch_i ? fetch_data_access_i : trans_data_access_q; // No new pointer fetch should be available in this case
Can't this just be: trans_data_access_o = trans_data_access_q;

I would expect that if trans_data_access_q = 1 in this state, then fetch_branch_i must be 0. Can you confirm and add an assertion for that?

2022-04-06 07:20 UTC, Silabs-ArjanB commented on rtl/cv32e40x_prefetcher.sv
> +        trans_data_access_q <= fetch_data_access_i;
This looks inconsistent. Should't it be: trans_data_access_q <= fetch_data_access_o;

2022-04-06 07:20 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +                    ) && !ex_wb_pipe_i.instr_meta.clic_ptr && instr_valid;
Why are ptr fetches excluded here? Isn't that changing the semantics of wb_valid?

2022-04-06 07:20 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> +  logic [10:0] mtvt_pc_mux;           // id of taken CLIC irq (to IF, EXC_PC_MUX, zeroed if not shv)
This should be 10 bits

2022-04-06 07:20 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mtvt_pc_mux = exc_cause;
This should be lower 10 bits of exc_cause only

2022-04-06 07:22 UTC, Silabs-ArjanB requested changes

2022-04-06 07:22 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  parameter bit       SMCLIC          = 0,
We should make sure that the write buffer has been flushed before a CLIC ptr fetch is attempted.

2022-04-06 07:24 UTC, silabs-oysteink commented on rtl/cv32e40x_mpu.sv
> +   input logic  core_data_access_i,    // Indicate that ongoing access is a data access from the IF stage
Fixed

2022-04-06 07:29 UTC, silabs-oysteink commented on rtl/cv32e40x_prefetcher.sv
> +        trans_data_access_q <= fetch_data_access_i;
I agree, fixed.

2022-04-06 07:34 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic [10:0] mtvt_pc_mux;           // id of taken CLIC irq (to IF, EXC_PC_MUX, zeroed if not shv)
Fixed

2022-04-06 07:40 UTC, silabs-oysteink commented on sva/cv32e40x_decoder_sva.sv
> +      !if_id_pipe.instr_meta.clic_ptr |-> (instr_rdata_i[1:0] == 2'b11);
Done

2022-04-06 07:41 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mtvt_pc_mux = exc_cause;
Fixed

2022-04-06 07:42 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign pending_nmi = (nmi_pending_q || ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err) &&
Well spotted, I will look into this.

2022-04-06 07:50 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +          ctrl_fsm_ns = FUNCTIONAL;
For CLIC pointers, I believe it is not possible to take a new interrupt when the pointer is still in the pipeline. We disable global interrupts in mstatus when taking starting the pointer fetch, and this needs to be re-enabled before we can take a new interrupt. No new instructions will complete before the pointer is out of the pipeline. We may however be interrupted by an external debug request, this could possibly cause some issues (I will have to dig a bit into this case). The PC of the pipeline stage containing the pointer would be the address of the pointer itself, so in theory we could be able to restart the pointer fetch - but more logic would be needed. Perhaps the 'lsu_interruptible' signal should only be allowed to go high when the write buffer is also empty?

When a (CLIC) pointer is in EX, there should be no valid instruction in WB, as the whole pipeline is killed when taking the interrupt and starting the pointer fetch. For Zc tablejumps this may not be the case though.

2022-04-06 09:17 UTC, Silabs-ArjanB requested changes

2022-04-06 09:17 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      cv32e40x_csr #(
Need block scope name on line above

2022-04-06 09:23 UTC, Silabs-ArjanB requested changes

2022-04-06 09:23 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +    mclicbase_n              = {csr_wdata_int[31:12], 12'h000};
Also make it obvious that signals as mie_n (and similar others if existing) are 0 when SMCLIC = 1 (I know these are not used at the moment when SMCLIC = 1, but it is still good to make it explicit)

2022-04-06 09:34 UTC, silabs-oysteink commented on rtl/cv32e40x_prefetcher.sv
> +        trans_data_access_o = fetch_branch_i ? fetch_data_access_i : trans_data_access_q; // No new pointer fetch should be available in this case
This should be true, I'll add the assertion and confirm.

2022-04-06 09:34 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      cv32e40x_csr #(
Fixed

2022-04-06 10:09 UTC, Silabs-ArjanB requested changes

2022-04-06 10:09 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +          //
MRET is not implemented according to CLIC spec when SMCLIC=1 (see page 20 of CLIC spec explaining the dependence on mcause.inhv)

2022-04-06 10:20 UTC, Silabs-ArjanB requested changes

2022-04-06 10:20 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +
mcause's minhv and mpil bitfields should be writeable by software when SMCLIC = 1. Our user manual also wrongly states minhv as a R bitfield (I will fix the documentation part)

2022-04-06 11:05 UTC, Silabs-ArjanB requested changes

2022-04-06 11:05 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +    mintthresh_n             = csr_wdata_int[7:0];
Width mismatch. Explicitly 0 top 24 bits.

2022-04-06 11:11 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +    mintthresh_n             = csr_wdata_int[7:0];
Fixed

2022-04-06 12:59 UTC, silabs-oysteink commented on sva/cv32e40x_rvfi_sva.sv
> +  /* todo: adapt to CLIC
I guarded the assertion with !SMCLIC and added a todo as this needs a bit more work.

Added issue #494

2022-04-06 13:29 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign pending_nmi = (nmi_pending_q || ex_wb_pipe_i.instr_valid && ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr.bus_resp.err) &&
Fixed

2022-04-06 14:16 UTC, silabs-oysteink commented on rtl/cv32e40x_prefetcher.sv
> +        trans_data_access_o = fetch_branch_i ? fetch_data_access_i : trans_data_access_q; // No new pointer fetch should be available in this case
I added the suggested assert, but is fails during single stepping into an interrupt handler. I added issue #496 to address this.

2022-04-06 14:21 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +                    ) && !ex_wb_pipe_i.instr_meta.clic_ptr && instr_valid;
I added issue #497 for this. Issue also addresses that we only signal wb_valid for the last part of a split misaligned LSU instruction.

2022-04-06 14:48 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +    mclicbase_n              = {csr_wdata_int[31:12], 12'h000};
Fixed

2022-04-06 14:52 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +          //
Added issue #498 for this

2022-04-06 14:56 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +
Fixed

2022-04-06 15:27 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      mtvec_n.mode             = csr_mtvec_init_i ? mtvec_q.mode : {1'b0, csr_wdata_int[0]};
Moved into https://github.com/openhwgroup/cv32e40x/issues/501

2022-04-07 06:24 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +          ctrl_fsm_ns = FUNCTIONAL;
I think at some point we talked about reverting the 'previous_exception' part to instead set alu_en for instructions with exceptions to make ex_valid go high, we could probably use that same method for pointers?

2022-04-07 07:15 UTC, silabs-oysteink commented
With SMCLIC==0: SEC clean and passes ci_check (using modified core-v-verif adapted to interface changes for clic)

2022-04-07 09:43 UTC, Silabs-ArjanB approved these changes

2022-04-07 09:43 UTC, merged