Implementation of mnxti
openhwgroup/cv32e40x pull request #506
Opened 2022-04-08 10:45 UTC by silabs-oysteink

MNXTI functionality should now be in.
Tested basic functionality of reading correct pointer addresses for pending interrupts when changing levels in the memory mapped registers.

SEC clean for SMCLIC=0

2022-04-08 13:46 UTC, Silabs-ArjanB requested changes
(We will discuss https://github.com/openhwgroup/cv32e40x/issues/507 separately as that issue was not introduced with this PR)

2022-04-08 13:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +  logic        csr_clic_pa_valid;
What does 'pa' stand for?

2022-04-08 13:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      end else if (mnxti_we) begin
If there is a mnxti write with side effects, then both mcause_we = 1 and mnxti_we = 1 and this block of code will not get executed.

2022-04-08 13:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +        mstatus_n     = mstatus_q;
I don't think these two lines are correct. The spec says 'All CSR instructions may be used with xnxti. The operation will be the same as the corresponding CSR instruction used with xstatus.', so shouldn't the already computed mstatus_n from line 571 do the trick?

2022-04-08 13:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      clic_pa_valid_o = csr_en_gated && (csr_waddr == CSR_MNXTI);
Would the following not be more logical?

clic_pa_valid_o = csr_we_int && (csr_waddr == CSR_MNXTI);

2022-04-08 13:51 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +  logic        csr_clic_pa_valid;
PointerAddress, I tried to make a short name, but this is probably too short. Would 'csr_clic_ptr_addr_valid' be better perhaps?

2022-04-08 13:53 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      end else if (mnxti_we) begin
That's right, we'll have to check the state for both write enables in the first if block I think.

2022-04-08 13:56 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      clic_pa_valid_o = csr_en_gated && (csr_waddr == CSR_MNXTI);
The address for the pointer should be returned even for pure reads, so checking using we_int would break the spec for 'csrr' for instance

2022-04-08 15:14 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +  logic        csr_clic_pa_valid;
You can keep this name; just add a comment on the lines where these signals are declared that contains at least the words 'pointer address'

2022-04-08 15:15 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      end else if (mnxti_we) begin
Maybe you can handle mnxti_we in the top/first if to get it correct?

2022-04-08 15:15 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      clic_pa_valid_o = csr_en_gated && (csr_waddr == CSR_MNXTI);
Yes, okay, thanks

2022-04-10 17:00 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      end else if (mnxti_we) begin
Fixed

2022-04-10 17:00 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +  logic        csr_clic_pa_valid;
Fixed

2022-04-10 17:30 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +        mstatus_n     = mstatus_q;
Agreed, fixed.

2022-04-11 07:55 UTC, Silabs-ArjanB approved these changes

2022-04-11 07:56 UTC, merged