Zc* table jumps
openhwgroup/cv32e40x pull request #552
Opened 2022-05-25 09:15 UTC by silabs-oysteink

Fully implemented table jumps for Zc*.

SEC clean when ZC_EXT=0

2022-05-25 10:46 UTC, Silabs-ArjanB requested changes

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +      PC_TBLJUMP :   branch_addr_n = (jvt_i.base << 6) + (if_id_pipe_o.instr.bus_resp.rdata[19:12] << 2);
We don't want a "+" here.

This needs to look like:

branch_addr_n = {jvt_addr_i + ctrl_fsm_i.jvt_pc_mux[7:0], 2'b00};

I will file an issue in the Zc TG to see if jvt.base can be declared WARL.

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +  jvt_t        jvt;
logic [21:0] jvt_addr;

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .jvt_i               ( jvt                      ),
.jvt_addr_i (jvt_addr),

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .jvt_o                      ( jvt                    ),
.jvt_addr_o (jvt_addr),

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +    jvt_n                    = {csr_wdata_int[31:6], 6'b000000};
This is as documented, but it leads to an adder in IF where we don't want it. This needs to become:

jvt_n = {csr_wdata_int[31:10], 10'b0000000000};

I will update spec and user manual.

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +  assign jvt_o = jvt_t'(jvt_q);
Only output address part

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +        id_ex_pipe_o.rf_we                  <= tbljmp_first ? 1'b0 : rf_we;  // Only the last part of table jumps write to the link register
Can't this be done inside the decoder or does it not fit there?

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +    instr_meta_n.compressed    = if_id_pipe_o.instr_meta.compressed;
This code looks weird. I did not try to understand it, but not all bits in instr_meta_n flow in the same way through the design, which is suspicious. If it cannot made to be more regular it at least deserves some comments. (Maybe this is a 'hidden FSM')

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +        if_id_pipe_o.last_op          <= last_op;
What will happen if there is a trigger match on the fetch from the table? It needs to be discarded.

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +        if (!prefetch_is_tbljmp_ptr) begin
How about the CLIC pointer fetch; should that also prevent certain updates?

2022-05-25 10:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +  assign tbljmp = (instr_decompressed.bus_resp.err || (instr_decompressed.mpu_status != MPU_OK)) ? 1'b0 : tbljmp_raw;
Add comment on 'why' this is needed

2022-05-25 11:03 UTC, silabs-oysteink commented on rtl/cv32e40x_compressed_decoder.sv
> +                if (instr[12:8] == 5'b00000) begin
Indeed, that looks much better.

2022-05-25 11:09 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +      PC_TBLJUMP :   branch_addr_n = (jvt_i.base << 6) + (if_id_pipe_o.instr.bus_resp.rdata[19:12] << 2);
I guess you mean "branch_addr_n = {jvt_addr_i, ctrl_fsm_i.jvt_pc_mux[7:0], 2'b00};" ? This was what I wanted to implement, but following the spec didn't leave enough bits tied to zero to make the concatenation.

2022-05-25 11:18 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  // Once the first part of a table jump has finished in WB, we are not allowed to take interrupts before the last part finishes. This can be detected when the last
Split load/stores are currently handled by the interruptible_o from the load_store_unit. for push/pop and multi moves I think it should be enough to add a single bit to the pipeline registers that tells that it is a multi operation instruction. I can't (at the moment) see any reason to be able to distinguish between them other than being able to block debug and interrupts.

2022-05-25 12:39 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +        id_ex_pipe_o.rf_we                  <= tbljmp_first ? 1'b0 : rf_we;  // Only the last part of table jumps write to the link register
At first I thought it could you deasser_we, but that would also deassert alu_en and the jump would not be taken. It can for sure be done in the decoder with something like 

`rf_we = (deassert_we_i || tbljmp_first) ? 1'b0 : rf_we`

2022-05-25 12:45 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +        id_ex_pipe_o.rf_we                  <= tbljmp_first ? 1'b0 : rf_we;  // Only the last part of table jumps write to the link register
Moved to decoder

2022-05-25 12:55 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    instr_meta_n.compressed    = if_id_pipe_o.instr_meta.compressed;
Added comments to explain. The idea is that the fields 'compressed' and 'tbljmp' needs to retain their value for table jumps, even for the second operation where a pointer is in the predecoder. The fields will be updated in 'the regular way' for all other cases than tablejump pointer. I see that this may be rewritten to be more clear though.

2022-05-25 13:01 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +        if_id_pipe_o.last_op          <= last_op;
Currently there are no triggers on the table fetch. The PC field (used in cs_registers for trigger matching) is kept identical for both the instruction itself and the table fetch. Whenever a pointer is fetched, the IF stage output 'ptr_in_if_o' will prevent trigger matches. Any trigger matches on the PC during the second operation would already have been taken during the first operation and the table fetch would not occur. I guess the spec isn't yet including information about trigger on table fetches?

2022-05-25 13:06 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +        if (!prefetch_is_tbljmp_ptr) begin
It's not needed for functional correctness, but we can possibly save some power by clock gating fields like 'instr_meta.compressed' as it doesn't make sense for CLIC pointers. The field 'instr.bus_resp.rdata' is already gated for both pointer types.

2022-05-25 13:16 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    .jvt_i               ( jvt                      ),
Fixed

2022-05-25 13:18 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign jvt_o = jvt_t'(jvt_q);
Fixed

2022-05-25 14:38 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  // Once the first part of a table jump has finished in WB, we are not allowed to take interrupts before the last part finishes. This can be detected when the last
Let's introduce an 'id' into the pipeline in a following PR to generalize the interrupt/debug behavior.

2022-05-25 14:40 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +      PC_TBLJUMP :   branch_addr_n = (jvt_i.base << 6) + (if_id_pipe_o.instr.bus_resp.rdata[19:12] << 2);
Okay

2022-05-25 14:48 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +        if_id_pipe_o.last_op          <= last_op;
0.70.3 does not contain the info related to trigger match. It is present in 0.70.4 and in our spec. It seems you already implemented the required behavior though (I did not yet see the related part in cs_registers when I wrote my question)

2022-05-25 14:50 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +    jvt_n                    = {csr_wdata_int[31:6], 6'b000000};
Zc spec needs to change as well. I assume that will happen as the current spec is awkward (and also not inline with for example mtvec which is a similar CSR)

2022-05-27 06:53 UTC, Silabs-ArjanB approved these changes

2022-05-27 06:53 UTC, Silabs-ArjanB commented on rtl/cv32e40x_controller_fsm.sv
> +  assign debug_allowed = lsu_interruptible_i && !fencei_ongoing && !xif_in_wb && !pointer_in_pipeline && !tbljmp_in_ex_wb;
I think this code could be more generic (I put it on my own list of things to possibly look at; okay for now)

2022-05-27 06:53 UTC, Silabs-ArjanB commented on rtl/cv32e40x_decoder.sv
> +  assign rf_we_o  = (deassert_we_i || tbljmp_first_i) ? 1'b0 : rf_we;
I think this could go all the way into I decoder. Okay like this.

2022-05-27 06:53 UTC, merged