Documented Atomics extension
openhwgroup/cv32e40x pull request #557
Opened 2022-05-27 13:44 UTC by Silabs-ArjanB

Do not merge to CV32E40S.

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

2022-05-27 13:50 UTC, silabs-oysteink requested changes

2022-05-27 13:50 UTC, silabs-oysteink commented on docs/user_manual/source/atomics.rst
> +Bus errors for ``lr.w`` and ``sc.w`` instructions are signaled with ``data_err_i``  = 0 and ``data_exokay_i`` = 0.
Should this be 'data_err_i = 1' ?

2022-05-30 05:39 UTC, Silabs-ArjanB commented on docs/user_manual/source/atomics.rst
> +Bus errors for ``lr.w`` and ``sc.w`` instructions are signaled with ``data_err_i``  = 0 and ``data_exokay_i`` = 0.
Yes. Should be fixed now.

2022-05-30 05:41 UTC, silabs-oysteink approved these changes

2022-05-30 05:41 UTC, merged