Added a 'first_op' to track the first operation of multi operation in…
openhwgroup/cv32e40x pull request #605
Opened 2022-06-30 12:42 UTC by silabs-oysteink

…structions through the pipeline.

RVFI will now only latch rs1/2_rdata when the first operation of a multi operation instruction is in the ID stage.

Added assertions to check that jump targets are stable when remaining in ID for multiple cycles.
Added assertion to check that RVFI may use operand_a_fw also for JALR instructions, although JALR uses a different bypass mux in RTL.

SEC clean.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-06-30 18:01 UTC, Silabs-ArjanB requested changes

2022-06-30 18:01 UTC, Silabs-ArjanB commented on sva/cv32e40x_id_stage_sva.sv
> +  // Only checking for JALR, as regular JAL do not use any RF or bypass operands for the jump target.
Add reason why this needs to be checked (i.e. because RVFI uses alu_jmpr instead of operand_a_fw)

2022-06-30 18:01 UTC, Silabs-ArjanB commented on sva/cv32e40x_id_stage_sva.sv
> +    (jmp_taken_id_ctrl_i && !ctrl_fsm_i.kill_id, jmp_target=jmp_target_o)
Nice; this looks intuitive

2022-07-01 06:20 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +        rs1_rdata  [STAGE_EX] <= first_op_id_i ? rs1_rdata_id : rs1_rdata[STAGE_EX];
My reasoning there is that all the other ID stage signals come from the if_id_pipe of either the core or the RVFI model. rs1/2_rdata are the only signals that may change in later cycles due to other instructions in either EX of WB through the bypass network.

2022-07-01 07:08 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +  assign first_op = prefetch_is_tbljmp_ptr ? 1'b0 : 1'b1;
I don't think that assertion would be correct for all stages. For instance for a PUSH instruction of length 10 as seen from the IF stage, the first one would have first && !last, then 8 with !first && !last and finally !first && last. For the first/last outputs from the load_store_unit I believe such an assertion would hold though.

2022-07-01 07:52 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rs1_rdata  [STAGE_EX] <= first_op_id_i ? rs1_rdata_id : rs1_rdata[STAGE_EX];
Thanks; agreed

2022-07-01 07:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +  assign first_op = prefetch_is_tbljmp_ptr ? 1'b0 : 1'b1;
Agreed; my remark did not make sense

2022-07-01 08:03 UTC, merged