Silabs oysteink wb controller
openhwgroup/cv32e40x pull request #63
Opened 2021-06-02 11:08 UTC by silabs-oysteink

This is a draft PR for the new WB-centric controller and associated pipeline changes.

Main changes are:

- Exceptions are propagated to WB stage
- CSR writes happens in WB
- RF has a single write port in WB
- Special instructions are propagated to WB
- All pipeline stages have a 'instr_valid' bit, indicating that it's current instructions is valid. Locally used inside stages to gate off secondary enable signales (like alu_en for instance)
- Controller may kill stages (effectively setting next_stage.instr_valid to zero in the next cycle)

Branches are still taken from EX and jumps from ID.

It is not yet feature complete (missing NMI, debug support and MPU exceptions from the LSU module).
The code is not properly cleaned up yet (port connections etc may be remnant from previous implementations).

Please review and comment, and I'll incorporate the feedback.

2021-06-02 11:25 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign mie_bypass_o = mie_q;//mie_we ? csr_mie_wdata & IRQ_MASK : mie_q;
I think this bypass may be removed.
If not removed it also creates a combinatorial loop as it feeds back into the interrupt controller and controller interrupt logic.

2021-06-03 12:06 UTC, Silabs-ArjanB requested changes

2021-06-03 12:06 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_controller_fsm.sv
> +      SLEEP: begin
Add assertion that when there is a WFI in WB there can be no load/store in EX.

2021-06-03 12:57 UTC, silabs-oysteink commented on cv32e40x_manifest.flist
> +${DESIGN_RTL_DIR}/cv32e40x_wb_controller_fsm.sv
Indeed, I kept the old file in case I needed to quickly run with the old controller in the very beginning. I will rename this.

2021-06-11 13:08 UTC, silabs-oysteink commented on cv32e40x_manifest.flist
> +${DESIGN_RTL_DIR}/cv32e40x_wb_controller_fsm.sv
Renamed back to original name

2021-06-14 09:07 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> +  //input  logic        dret_id_i,
Fixed

2021-06-14 09:07 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> +  cv32e40x_wb_controller_fsm
Fixed

2021-06-14 09:25 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> +  cv32e40x_wb_controller_fsm
Fixed

2021-06-14 09:25 UTC, silabs-oysteink commented on rtl/cv32e40x_controller.sv
> +  controller_fsm_i (
Fixed rst_n connection

2021-06-14 09:26 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  // Detect when a CSR read is in ID
Done

2021-06-14 09:34 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    .wb_pc_i             ( ex_wb_pipe.pc     ),
Fided wb_pc

2021-06-14 09:34 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
>      .pc_id_i                    ( if_id_pipe.pc          ),
Fixed

2021-06-14 09:35 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    //.dret_id_i                      ( dret_insn              ),
Fixed

2021-06-14 09:35 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_addr     =  csr_num_e'((ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid) ? ex_wb_pipe_i.csr_addr : '0);
Fixed

2021-06-14 09:35 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_addr     =  csr_num_e'((ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid) ? ex_wb_pipe_i.csr_addr : '0);
Good question, added a TODO for now

2021-06-14 09:36 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign mie_bypass_o = mie_q;//mie_we ? csr_mie_wdata & IRQ_MASK : mie_q;
Removed and renamed.

2021-06-14 09:39 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +    if(id_ex_pipe_i.csr_access && id_ex_pipe_i.instr_valid) begin
I'm pretty sure we can remove it now that we perform CSR writes in EX. It was used to not allow updates for CSR rdata in case of stalls (CSR writes would be written the first cycle in EX, rdata updated/overwritten the second). Now that we perform CSR writes in WB the CSR rdata will not change for stalls in EX since the write will also be stalled in the same stage.

2021-06-14 09:45 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +  assign alu_en_gated = id_ex_pipe_i.alu_en && id_ex_pipe_i.instr_valid && !kill_ex_i;
Fixed, with exception for IF-stage where the kill is used directly inside the alignment_buffer. Might revisit that one later

2021-06-14 09:48 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +    if (alu_en_gated)
I was just 'blindly' killing all enables. I see not that it probably won't matter, as the instr_valid will gate off the EX pipe outputs regardlessly.

2021-06-14 09:49 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +    .enable_i            ( alu_en_gated               ),
Awaiting changes by Øivind/Halfdan for ALU/MUL/DIV

2021-06-14 09:49 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +      ex_wb_pipe_o.csr_addr       <= '0;
Done

2021-06-14 09:50 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
>          // so we just flush the current one out of the pipe
Updated

2021-06-14 09:50 UTC, silabs-oysteink commented on rtl/cv32e40x_ex_stage.sv
> +        //ex_wb_pipe_o.rf_we <= 1'b0;
Removed

2021-06-14 09:51 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +    input  logic        kill_id_i,
Removed

2021-06-14 09:51 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +  assign clear_instr_valid_o = id_ready_o /*| halt_id_i*/ | branch_taken_ex_o; // TODO: branch_taken implies halt_id? Check with formal
Cleaned up and moved

2021-06-14 09:51 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +  assign id_ready_o = (!csr_stall_i && !multi_cycle_id_stall && !jr_stall_i && !load_stall_i && ex_ready_i && !halt_id_i  && !(id_ex_pipe_o.wfi_insn && id_ex_pipe_o.instr_valid));
Done

2021-06-14 09:52 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +      PC_FENCEI:    branch_addr_n = wb_pc_i + 4; // jump to next instr forces prefetch buffer reload
TODO added

2021-06-14 09:52 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +        //$display("IF_PC 0 %08x", pc_if_o);
Fixed.

2021-06-14 09:53 UTC, silabs-oysteink commented on rtl/cv32e40x_load_store_unit.sv
> +  assign block_data_req = kill_ex_i || id_ex_pipe_i.instr.bus_resp.err ||
Done, using deassert_we in the decoder to convert instructions with exception to NOP in the ID stage.

2021-06-14 10:44 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +  assign exception_in_wb = (ex_wb_pipe_i.illegal_insn       ||
Ordered

2021-06-14 10:54 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +          ctrl_fsm_ns = BOOT_SET;
Done

2021-06-14 11:02 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +        kill_if_o   = 1'b1; // TODO: May remove this
Fixed

2021-06-14 11:13 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +            end else if( id_ex_pipe_i.instr_valid) begin
Agreed that it is ok as it is.

2021-06-14 11:13 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +            end else if( if_id_pipe_i.instr_valid) begin
Agreed that it is ok as it is

2021-06-14 12:13 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +
For exceptions from IF/ID, all write enables are suppressed in the ID stage. For later exceptions (not yet implemented) they would get their write enables suppressed in the stage they occur.

2021-06-14 12:14 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +        end else if( branch_taken_ex_i ) begin
instr_valid_ex was factored in (signal calculated in ID stage). Moved this to the controller for clarity.

2021-06-14 12:15 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +        end else if ( jump_in_id ) begin
Fixed

2021-06-14 12:26 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +      SLEEP: begin
Added assertion

2021-06-14 12:26 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +            pc_set_o = !jr_stall_i;
Factored jr_stall into jump_taken. Added todo for mepc hazard.

2021-06-14 12:35 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_controller_fsm.sv
> +  // Detect when data_req has been clocked, and lsu insn is still in EX
Not really, this is checking if a data_req_o has been high for at least one clock cycle, while the outstanding counter counts up on trans_valid && trans_ready.

2021-06-14 12:36 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +                         ex_wb_pipe_i.csr_en   ? ex_wb_pipe_i.rf_wdata :
It shouldn't have changed, reverted to how it was.

2021-06-14 12:38 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +  assign wb_valid_o    = lsu_ready_wb_i && !halt_wb_i && instr_valid;
The wb_valid_o isn't really used by anything other than the rvfi. Factoring in halt_wb_i to indicate that the instruction hasn't yet retired since it has been halted by the controller.

2021-06-14 12:38 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +//typedef enum logic [4:0] { RESET, BOOT_SET, SLEEP, WAIT_SLEEP, FIRST_FETCH,
Done

2021-06-14 12:38 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic         csr_en;
csr_access should be removeable now. Leaving that for a separate PR after the controller is merged.

2021-06-14 12:39 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    (kill_wb_o) |-> (csr_op_i == CSR_OP_READ) )
Added todo in cs_registers.sv

2021-06-14 12:42 UTC, silabs-oysteink commented on sva/cv32e40x_core_sva.sv
> +        !(ex_wb_pipe_i.instr.bus_resp.err || (ex_wb_pipe_i.instr.mpu_status != MPU_OK) || ex_wb_pipe_i.illegal_insn) &&
I will revisit these

2021-06-17 10:52 UTC, silabs-oysteink commented
40X now passes ci_check with ISS disabled for the new controller/pipeline. This PR contains a lot of TODO's and things we know need to be updated. This PR will however get verification started in enabling the new pipeline/controller within core-v-verif, as this PR breaks a lot of cross module references and the debug coverage.

2021-06-17 12:13 UTC, Silabs-ArjanB approved these changes

2021-06-17 12:13 UTC, merged