Converted unique case to regular case with defaults in load_store_uni…
openhwgroup/cv32e40x pull request #635
Opened 2022-08-02 12:58 UTC by silabs-oysteink

…t and divider to avoid warnings at reset during simulation.

Adde default to other case statements where defaults were missing.

SEC clean.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-08-02 12:58 UTC, silabs-oysteink commented
Should fix issue #596

2022-08-02 14:24 UTC, Silabs-ArjanB requested changes

2022-08-02 14:24 UTC, Silabs-ArjanB commented on rtl/cv32e40x_compressed_decoder.sv
> +            default:;
This does not seems to correspond to 'Converted unique case to regular case with defaults', does it? (Difficult in this view to see if this default belongs to a unique case or not

2022-08-03 06:08 UTC, silabs-oysteink commented on rtl/cv32e40x_div.sv
> +      default:;
Added a default value for alu_clz_data.

2022-08-03 06:09 UTC, silabs-oysteink commented on rtl/cv32e40x_compressed_decoder.sv
> +                    default:;
Most cases that did not have a default got one added, and the type (unique/regular) was unchanged. The design currently has a mix of 'case' and 'unique case', but all cases should not have a default clause.

2022-08-03 11:17 UTC, Silabs-ArjanB approved these changes

2022-08-03 11:17 UTC, merged