Removed exception checking in IF stage
openhwgroup/cv32e40x pull request #641
Opened 2022-08-17 11:20 UTC by silabs-oysteink

Sequenced instructions and table jumps will proceed to ID stage regardless of MPU status and bus error.
Using deassert_we logic in ID stage to avoid side effects.

NOT SEC clean as the difference in deassertion logic impacts the prefetcher.

2022-08-18 15:45 UTC, Silabs-ArjanB requested changes

2022-08-19 06:37 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  input  logic        abort_op_if_i,              // IF stage contains an operation that will aborted (bus error or MPU exception)
Will fix this

2022-08-19 06:38 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign ctrl_fsm_o.mhpmevent.wb_invalid    = !(wb_valid_i && (last_op_wb_i || abort_op_wb_i));
I think that makes sense. I'm not sure why the last_op was included in the first place. With my proposed code a long pop instruction would show high grader of underutilized WB/rf_we, while in practice a lot of writes would be done. I'll change the expression and the corresponding assertion

2022-08-19 06:44 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +        if (id_valid_i && ex_ready_i && first_op_id_i && !last_op_id_i && !ctrl_byp_i.id_stage_abort) begin // id_valid implies if_id_pipe.instr.valid
I think it is not needed. For any sequence except table jumps, abort_op in ID may only happen on the very first operation. Either the instruction itself is faulted from IF, or we have an abort in ID. In that case, the flag will not be set and there should be no need to clear it on abort_op. For table jumps we may have abort_op on either of the two operations, in the case of abort on the first operation the explanation above for pops will hold. If an abort occurs on the last operation, the flag would be cleared anyway by the last_op. 

I will add the abort_op anyway though, as it likely won't affect timing and the code will be more consistent.

2022-08-19 07:17 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +  localparam bit ZC_EXT = 1;
It was a mistake, we should wait with the enabling until verification is ready.

2022-08-19 12:23 UTC, Silabs-ArjanB approved these changes

2022-08-19 12:23 UTC, merged