Add support for RV32E
openhwgroup/cv32e40x pull request #695
Opened 2022-11-02 12:15 UTC by silabs-oivind

SEC clean when parameter RV32=RV32I

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

2022-11-04 07:29 UTC, Silabs-ArjanB requested changes

2022-11-08 10:31 UTC, silabs-oivind commented on rtl/cv32e40x_decoder.sv
> +    if (if_id_pipe_i.illegal_c_insn || rf_illegal_addr) begin
Updated.

2022-11-08 10:32 UTC, silabs-oivind commented on rtl/cv32e40x_id_stage.sv
> +          xif_issue_if.issue_req.rs_valid[0] = (ctrl_byp_i.operand_a_fw_mux_sel == SEL_REGFILE) ?
Because values can be forwarded from EX or WB stage. Upon forwarding, the RF address check in the decode stage will not be applicable.

2022-11-11 09:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_decoder.sv
> +      assign dec_a_rf_illegal_addr = (decoder_a_ctrl_int.rf_re[0] && rf_illegal_raddr_o[0]) ||
Assign this signal to 1'b0 in 'else' part of generate statement so that we do net get floating signals (even though they are not used). Same remark for other similar signals.

2022-11-11 09:42 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +          xif_issue_if.issue_req.rs_valid[0] = (ctrl_byp_i.operand_a_fw_mux_sel == SEL_REGFILE) ?
I would say that the RF address check from the decoder stage would always apply, so it should be:

          xif_issue_if.issue_req.rs_valid[0] = !rf_illegal_raddr[0];

(Of course in reality ctrl_byp_i.operand_a_fw_mux_sel == SEL_REGFILE will always hold and then your code proposal and my proposal are the same. Also note that stalls/bypass usage is not correct yet, see https://github.com/openhwgroup/cv32e40x/issues/277)

2022-11-11 09:43 UTC, Silabs-ArjanB requested changes
Please also see the XIF related comments.

2022-11-11 09:43 UTC, Silabs-ArjanB commented on rtl/cv32e40x_id_stage.sv
> +          xif_issue_if.issue_req.rs_valid[1] = (ctrl_byp_i.operand_b_fw_mux_sel == SEL_REGFILE) ?
Same as above; I think the code should be simplified.

2022-11-11 10:07 UTC, silabs-oivind commented on rtl/cv32e40x_id_stage.sv
> +          xif_issue_if.issue_req.rs_valid[0] = (ctrl_byp_i.operand_a_fw_mux_sel == SEL_REGFILE) ?
Of course, you're right. Updated.

2022-11-11 10:07 UTC, silabs-oivind commented on rtl/cv32e40x_decoder.sv
> +      assign dec_a_rf_illegal_addr = (decoder_a_ctrl_int.rf_re[0] && rf_illegal_raddr_o[0]) ||
Updated.

2022-11-11 10:22 UTC, Silabs-ArjanB approved these changes

2022-11-11 10:23 UTC, merged