Removed POINTER_FETCH state from controller_fsm
openhwgroup/cv32e40x pull request #696
Opened 2022-11-08 11:56 UTC by silabs-oysteink

POINTER_FETCH fsm state replaced by a separate state flop. Controller stays in FUNCTIONAL while handling CLIC SHV interrupts.

Mret which restarts CLIC pointer fetch due to mcause.minhv and mcause.mpp will now get its 'last_op' bit set to 0 in the ID stage, and the following CLIC pointer will complete the sequence. CSR updates only happen when the pointer reaches WB.

NOT SEC clean
- Master has bugs (possible deadlock while single stepping mret with CLIC pointers, wrong pipeline stage used for excluding CLIC pointers from incrementing minstret).
- Minstret will now only update for mret when the CLIC pointer is done (or when the mret reaches WB if no CLIC pointer fetch is restarted)

2022-11-09 15:46 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  logic mret_pointer_in_wb;
Renamed

2022-11-09 15:46 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +  assign mret_pointer_in_wb = ex_wb_pipe_i.instr_meta.clic_ptr && ex_wb_pipe_i.instr_valid && !ex_wb_pipe_i.first_op && !exception_in_wb;
Moved exception_in_wb

2022-11-09 15:47 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +    // Keep clear_minhv out of unique case as it may happen at the same time as csr_restore_mret
Refactored code and made the case unique again

2022-11-09 15:47 UTC, silabs-oysteink commented on rtl/cv32e40x_id_stage.sv
> +  // Mrets with the mcause conditions not true will be normal single operation instructions.
Comments added

2022-11-09 15:47 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +  logic [1:0]        prefetch_is_clic_ptr;
Done

2022-11-10 10:43 UTC, Silabs-ArjanB requested changes

2022-11-10 10:43 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +      // In the case of mret restarting CLIC pointer fetchces, minhv is cleared while
fetchces -> fetches

2022-11-10 10:43 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +  assign first_op_o =  prefetch_is_clic_ptr[1] ? 1'b0 :            // clic pointer caused by mret, must be !first && last
Keep seq_valid highest priority, so:

```
>   assign first_op_o = seq_valid               ? seq_first :     // Sequenced instruction (including table jump)
>                       prefetch_is_clic_ptr[1] ? 1'b0 :          // CLIC pointer caused by mret
>                                               : 1'b1;           // Regular instruction and regular CLIC pointer
> 
>   assign last_op_o = seq_valid               ? seq_last :       // Sequenced instruction (including table jump)
>                      prefetch_is_clic_ptr[1] ? 1'b1 :           // CLIC pointer caused by mret
>                                              : 1'b1;            // Regular instruction and regular CLIC pointer


```

2022-11-10 10:43 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +  input logic           clic_ptr_fetching_n
Rename this one as well

2022-11-10 10:43 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                  !((mret_clic_ptr_in_wb || non_mret_clic_ptr_in_wb) && !ctrl_fsm_o.kill_wb)))
!ctrl_fsm_o.kill_wb should not be needed

2022-11-10 10:43 UTC, Silabs-ArjanB commented on sva/cv32e40x_rvfi_sva.sv
> +   input logic             mret_clic_pointer_wb,
mret_clic_pointer_wb -> mret_clic_ptr_wb

2022-11-10 10:43 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  logic         mret_clic_pointer_wb;
mret_clic_pointer_wb -> mret_clic_ptr_wb

2022-11-10 10:43 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  assign wb_valid_subop    = wb_valid_i && !(clic_ptr_wb_i);
The semantics of these two signals now conflict with the comment on line 1069. I think it should be such that  wb_valid_lastop = 1 keeps implying wb_valid_subop = 1.

Can that be done? (I did not review the rest of this file yet)

2022-11-11 07:01 UTC, silabs-oysteink commented on rtl/include/cv32e40x_pkg.sv
> +  logic        csr_restore_mret_pointer; // Restore CSR due to mret followed by CLIC
Fixed

2022-11-11 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +                  clic_ptr_fetching_n = 1'b1;
Removed flushing of EX and WB for mret which restarts pointer fetches.

2022-11-11 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +              clic_ptr_fetching_n = 1'b1;
Renamed and updated semantics of the flop.

2022-11-11 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +      // In the case of mret restarting CLIC pointer fetchces, minhv is cleared while
Fixed

2022-11-11 07:02 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +  assign first_op_o =  prefetch_is_clic_ptr[1] ? 1'b0 :            // clic pointer caused by mret, must be !first && last
Fixed

2022-11-11 07:02 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +  input logic           clic_ptr_fetching_n
Done

2022-11-11 07:02 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                  !((mret_clic_ptr_in_wb || non_mret_clic_ptr_in_wb) && !ctrl_fsm_o.kill_wb)))
True, removed it

2022-11-11 07:03 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +  assign wb_valid_subop    = wb_valid_i && !(clic_ptr_wb_i);
Should be up to date now

2022-11-11 09:05 UTC, Silabs-ArjanB requested changes

2022-11-11 10:22 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +          if ((clic_ptr_in_id || mret_ptr_in_id) && id_valid_i && ex_ready_i) begin
Agreed, removing mret_ptr_in_id is also SEC clean (no mret should be in the pipeline at all when clic_ptr_in_id is 1)

2022-11-11 12:13 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                  !(mret_ptr_in_wb || clic_ptr_in_wb)))
Done

2022-11-11 12:14 UTC, silabs-oysteink commented on sva/cv32e40x_decoder_sva.sv
> +  // CLIC and mret pointers in ID will deassert all write enables.
Updated assertions, the second assertion above uses the *en_o signals from the decoder, as the deassert is deasserting the decoder_ctrl_mux outputs.

2022-11-11 12:14 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +        // sequence_in_progress_id is set, clear when last_op retires or ID stage is killed
Refactored code back to original. SEC clean.

2022-11-11 12:15 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_fsm.sv
> +        if (clic_ptr_in_progress_id_clear || ctrl_fsm_o.kill_id) begin
Removed killing of this signal on kill_id, added assertion to prove that kill_id can never be asserted when a clic_ptr is pending.

2022-11-11 12:15 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +        if ((last_op_if_i || abort_op_if_i) && !(clic_ptr_if_i || mret_ptr_if_i)) begin
It is actually not needed so I removed it. Introduced by mistake when making separate clic_ptr and mret_ptr flags.

2022-11-11 12:16 UTC, silabs-oysteink commented
Updated according to latest feedback, SEC clean for both ZC_EXT=0 and ZC_EXT=1.

2022-11-14 07:37 UTC, Silabs-ArjanB approved these changes

2022-11-14 07:37 UTC, merged