Debug triggers refactor
openhwgroup/cv32e40x pull request #697
Opened 2022-11-09 12:16 UTC by silabs-oysteink

Moved all trigger related code to a new module - debug_triggers.sv. CSR decoding is still done in cs_registers, but the actual CSR instances for trigger CSRs are moved to the new submodule. Trigger matches (instruction address only) is done in this new module.

This is the first step towards configurable number of triggers and the addition of new trigger types.

SEC clean

Do not merge until PR #696 is merged. This is to make the merge to cv32e40s easier.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-11-09 16:09 UTC, Silabs-ArjanB requested changes

2022-11-09 16:09 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +    .rd_data_o          ( tdata1_rdata          )
Keep adhering to the original signal naming strategy everywhere (we need separate names for WARL resolution, etc.), so this line should be:

    .rd_data_o          ( tdata1_q              )

and then you add:

  assign tdata1_rdata = tdata1_q;

Same for tdata2.

2022-11-09 16:09 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +
Remove 2 empty lines

2022-11-09 16:09 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +
Remove 1 line

2022-11-10 07:16 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +    .rd_data_o          ( tdata1_rdata          )
Done

2022-11-10 07:16 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +
Done

2022-11-10 07:16 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +
Done

2022-11-10 07:29 UTC, Silabs-ArjanB approved these changes

2022-11-11 08:30 UTC, silabs-oysteink commented
Merging now to enable merging to CV32E40S. #696 should be merged separately.

2022-11-11 08:30 UTC, merged