Divider and EX stage cleanup
openhwgroup/cv32e40x pull request #70
Opened 2021-06-09 14:45 UTC by silabs-oivind

2021-06-09 15:56 UTC, Silabs-ArjanB commented on bhv/cv32e40x_wrapper.sv
> +    core_i.ex_stage_i.div_i cv32e40x_alu_div_sva #(.C_WIDTH (C_WIDTH), .C_LOG_WIDTH (C_LOG_WIDTH)) div_sva (.*);
Rename cv32e40x_alu_div to cv32e40x_div

2021-06-10 14:57 UTC, Silabs-ArjanB requested changes

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +    // Clock and reset
Add comment on meaning of the parameters (I am also fine with hard coding here as I wonder if these parameters would actually work given that not all signals have parameterized width)

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +    output logic [31:0]        alu_clz_input_o,
Maybe rename alu_clz_input_* to alu_clz_data_* everywhere as I think having 'input' as part of a signal name ending on _o is confusing.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +	       div_valid  = valid_i;
Indentation is off (here and similarly on a couple of lines below); it seems that a 'tab' has been used.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +     div_valid  = 1'b0;
div_valid seems always equal to valid_i; why do we need this signal?

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +  logic op_b_is_zero;
Maybe rename to div_op_b_is_zero

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +  logic dig_op_b_neg;
Why 'dig_' instead of 'div_'?

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +          alu_clz_input_o = ~op_b_i;
Don't we already have this signal in the ALU? If so, just add a 'todo' as we might not want to re-use that because of leakage reasons.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_alu_div.sv
> +endmodule : cv32e40x_alu_div
Rename module and file (and update manifest): alu_div -> div

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +  // This is done becase the divider utilizes the shifter in the ALU to shift the divisor (div_i.op_b_i), and the ALU
Can you add a 'COCO analysis todo' here (whether it is okay from a leakage perspective to use the ALU at all for DIV/REM instructions)

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +      .const_div_cycles_en_i ( 1'b0                       ), // TODO connect to CSR
Can you rename the pin to data_ind_timing_i (the CSR bitfield will be called dataindtiming)

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +      .op_a_i                ( id_ex_pipe_i.alu_operand_b ),
This is even more confusing than I originally thought (so we swap in the decoder and then partially swap back here); maybe move the comment from line 153 here and on the next line.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +      .alu_op_b_shifted_i ( div_op_a_shifted  ),
and a comment here :-)

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_ex_stage.sv
> +  assign ex_downstream_ready = lsu_ready_ex_i && wb_ready_i;
This does not look correct, or the lsu signal has a misleading name. lsu_ready_ex_i does not seem to be a downstream signal.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mult.sv
> +    end else if (valid_i && (operator_i == MUL_H)) begin
Can you add a todo in the multiplier to make it look more like the divider for the scenario in which valid_i is retracted during a multi-cycle operation. The divider's code is more intuitive for that case.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on rtl/include/cv32e40x_pkg.sv
> + ALU_AND   = 4'b0110,
Did you try to pick a 'good encoding' or is this enumeration still more or less random? If you think we can pick a smarter encoding please add a todo.

2021-06-10 14:57 UTC, Silabs-ArjanB commented on sva/cv32e40x_mult_sva.sv
> +                     !ready |=> $stable(valid_i)) else `uvm_error("mult", "Enable changed when MULH active")
Please check with Øystein; I am quite sure that we are purposely going to break this assertion soon.

2021-06-11 06:49 UTC, silabs-oivind commented on rtl/cv32e40x_alu.sv
> +  assign shift_arithmetic = div_shift_en_i ? 1'b0 :
The value of alu_operator is not currently updated during DIV*/REM* and can have any value. We could update it and control the shifter through alu_operator, but I believe it's more readable to use the divider interface to explicitly override shifter and CLZ control. I've added some comments to clarify.

2021-06-11 06:50 UTC, silabs-oivind commented on bhv/cv32e40x_wrapper.sv
> +    core_i.ex_stage_i.div_i cv32e40x_alu_div_sva #(.C_WIDTH (C_WIDTH), .C_LOG_WIDTH (C_LOG_WIDTH)) div_sva (.*);
Done

2021-06-11 06:50 UTC, silabs-oivind commented on rtl/cv32e40x_alu.sv
> +    begin : gen_div_clz_inpu_rev
Updated.

2021-06-11 06:53 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +    // Clock and reset
Went with hardcoding.

2021-06-11 06:56 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +    output logic [31:0]        alu_clz_input_o,
Updated.

2021-06-11 07:00 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +	       div_valid  = valid_i;
Fixed.

2021-06-11 07:18 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +     div_valid  = 1'b0;
It's a leftover from when alu_operator was used for the divider. Replaced the case statement with simple assignements on div_rem and div_valid. Using valid_i in the place of div_valid.

2021-06-11 07:21 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +  logic op_b_is_zero;
Don't see a need to div_* prefix. This signal is 1 when the op_b_i is 0.

2021-06-11 07:22 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +  logic dig_op_b_neg;
Typo. Renamed to op_b_is_neg. this signal indicates when op_b_i is negative.

2021-06-11 07:24 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +          alu_clz_input_o = ~op_b_i;
No, we have ~operand_b_i in the ALU (which would be op_a_i in the divider...)

2021-06-11 07:25 UTC, silabs-oivind commented on rtl/cv32e40x_alu_div.sv
> +endmodule : cv32e40x_alu_div
Done

2021-06-11 07:27 UTC, silabs-oivind commented on rtl/cv32e40x_ex_stage.sv
> +  // This is done becase the divider utilizes the shifter in the ALU to shift the divisor (div_i.op_b_i), and the ALU
Added.

2021-06-11 07:28 UTC, silabs-oivind commented on rtl/cv32e40x_ex_stage.sv
> +      .const_div_cycles_en_i ( 1'b0                       ), // TODO connect to CSR
Done

2021-06-11 07:35 UTC, silabs-oivind commented on rtl/cv32e40x_ex_stage.sv
> +      .op_a_i                ( id_ex_pipe_i.alu_operand_b ),
Yep, it's quite confusing. Added more comments.

2021-06-11 07:35 UTC, silabs-oivind commented on rtl/cv32e40x_ex_stage.sv
> +      .alu_op_b_shifted_i ( div_op_a_shifted  ),
Done

2021-06-11 07:40 UTC, silabs-oivind commented on rtl/include/cv32e40x_pkg.sv
> + ALU_AND   = 4'b0110,
It's random. Added a TODO.

2021-06-11 07:54 UTC, silabs-oivind commented on sva/cv32e40x_mult_sva.sv
> +                     !ready |=> $stable(valid_i)) else `uvm_error("mult", "Enable changed when MULH active")
We will. I added a TODO

2021-06-11 08:35 UTC, silabs-oivind commented on rtl/cv32e40x_mult.sv
> +    end else if (valid_i && (operator_i == MUL_H)) begin
Done

2021-06-14 07:47 UTC, silabs-oivind commented on rtl/cv32e40x_ex_stage.sv
> +  assign ex_downstream_ready = lsu_ready_ex_i && wb_ready_i;
Removed ex_downstream_ready and reverted to using lsu_ready_ex_i && wb_ready_i in generation of ex_ready_o/ex_valid_o. Added a TODO to remove the wb_ready_i from the fanin of ex_valid_o

2021-06-14 08:22 UTC, Silabs-ArjanB approved these changes

2021-06-14 08:22 UTC, merged