Added support for DBG_NUM_TRIGGERS parameter
openhwgroup/cv32e40x pull request #700
Opened 2022-11-16 13:30 UTC by silabs-oysteink

Added support for DBG_NUM_TRIGGER parameter.If 0, the debug_triggers module will not be instantiated and any access to trigger CSR will result in an illegal instruction.

debug_triggers will instantiate DBG_NUM_TRIGGERS instances of tdata1 and tdata2 and perform instruction address match checks for any enabled triggers.

Converted trigger type 2 (mcontrol) to 6 (mcontrol6) and updated trigger match to take EXECUTE and M bit into account. (Passed modified debug_trigger_test). Reset value for tdata1 is updated to reflect mcontrol6.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-11-16 14:11 UTC, Silabs-ArjanB requested changes

2022-11-16 14:11 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +  assign tselect_rdata_o  = tselect_q;
Add todo on tinfo_rdata_o; it still need to be updated

2022-11-17 09:15 UTC, silabs-oysteink commented on bhv/cv32e40x_wrapper.sv
> +         .csr_tdata1_n_i           ( core_i.cs_registers_i.triggers.debug_triggers_i.tdata1_n             ), // If DBG_NUM_TRIGGERS=0 this connection will fail
Refactored code to always include debug_triggers and checking for DBG_NUM_TRIGGERS inside debug_triggers instead. Makes RVFI connection equal for any value of DBG_NUM_TRIGGERS.

2022-11-17 09:15 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +    tselect_n     = (csr_wdata_i < DBG_NUM_TRIGGERS) ? csr_wdata_i : (DBG_NUM_TRIGGERS - 1);
Fixed

2022-11-17 09:15 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +  assign tselect_rdata_o  = tselect_q;
Added todo.

2022-11-17 09:24 UTC, Silabs-ArjanB approved these changes

2022-11-17 09:24 UTC, merged