Added trigger type 2 (mcontrol)
openhwgroup/cv32e40x pull request #750
Opened 2023-01-03 14:31 UTC by silabs-oysteink

Adding label do-not-merge as we may need an ISS update due to the changes in tdata1 legal values and reset value.

2023-01-03 15:24 UTC, Silabs-ArjanB requested changes

2023-01-03 15:24 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_match_resolve(csr_wdata_i[MCONTROL2_6_MATCH_HIGH:MCONTROL2_6_MATCH_LOW]), // match, WARL(0,2,3) 10:7
Also rename mcontrol6_match_resolve -> mcontrol2_6_match_resolve

2023-01-03 15:24 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_u_resolve(csr_wdata_i[MCONTROL2_6_U]),     // zero, U 3
Also rename mcontrol6_u_resolve -> mcontrol2_6_u_resolve

2023-01-03 15:24 UTC, Silabs-ArjanB commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_match_resolve(csr_wdata_i[MCONTROL2_6_MATCH_HIGH:MCONTROL2_6_MATCH_LOW]), // match, WARL(0,2,3) 10:7
same here and other places

2023-01-03 15:46 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_match_resolve(csr_wdata_i[MCONTROL2_6_MATCH_HIGH:MCONTROL2_6_MATCH_LOW]), // match, WARL(0,2,3) 10:7
Fixed

2023-01-03 15:46 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_u_resolve(csr_wdata_i[MCONTROL2_6_U]),     // zero, U 3
Fixed

2023-01-03 15:46 UTC, silabs-oysteink commented on rtl/cv32e40x_debug_triggers.sv
> +                        mcontrol6_match_resolve(csr_wdata_i[MCONTROL2_6_MATCH_HIGH:MCONTROL2_6_MATCH_LOW]), // match, WARL(0,2,3) 10:7
Fixed

2023-01-03 15:59 UTC, Silabs-ArjanB approved these changes

2023-01-12 08:10 UTC, Silabs-ArjanB requested changes
The comment and behavior at line https://github.com/openhwgroup/cv32e40x/blob/55d4a5b1392aa76cda099328a901a6b28fe9e5b5/rtl/cv32e40x_debug_triggers.sv#L192 do not reflect tdata1.type = 0xF being the resolution value.

2023-01-17 09:17 UTC, Silabs-ArjanB approved these changes

2023-01-23 08:50 UTC, merged