Added backpressure from WB to the MPU and WPT responses.
openhwgroup/cv32e40x pull request #764
Opened 2023-01-18 12:15 UTC by silabs-oysteink

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2023-01-18 13:35 UTC, silabs-oysteink commented
This should solve issue #653

2023-01-19 08:26 UTC, Silabs-ArjanB requested changes

2023-01-19 08:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +        .core_resp_ready_i   ( ready_0_i         ),
Introduce wpt_resp_ready signal

2023-01-19 08:26 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +    .core_resp_ready_i    ( ready_0_i          ),
Introduce mpu_resp_ready signal

2023-01-20 08:26 UTC, silabs-oysteink commented on rtl/cv32e40x_load_store_unit.sv
> +        .core_resp_ready_i   ( ready_0_i         ),
Fixed

2023-01-20 08:26 UTC, silabs-oysteink commented on rtl/cv32e40x_load_store_unit.sv
> +    .core_resp_ready_i    ( ready_0_i          ),
Fixed

2023-01-20 08:39 UTC, Silabs-ArjanB requested changes

2023-01-20 08:39 UTC, Silabs-ArjanB commented on rtl/cv32e40x_load_store_unit.sv
> +  logic           wpt_resp_ready;
You need to actually assign these new signals as well

2023-01-20 08:43 UTC, silabs-oysteink commented
I found an issue in formal which need some attention before merging.

2023-01-20 09:18 UTC, Silabs-ArjanB approved these changes

2023-01-20 09:19 UTC, merged