Reverted WPT/MPU backpressure and applied sticky LSU bits in WB instead
openhwgroup/cv32e40x pull request #771
Opened 2023-01-27 14:11 UTC by silabs-oysteink

2023-01-27 15:23 UTC, Silabs-ArjanB requested changes

2023-01-27 15:23 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_wpt_match = lsu_wpt_match_i || lsu_wpt_match_q;
The wpt and mpu status assignments should use the same RTL style

2023-01-27 15:23 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +        lsu_valid_q <= lsu_valid;
I think the code would be clearer if you would have something like:
        if (lsu_valid) begin
            lsu_valid_q <= 1'b1;
            lsu_wpt_match_q <= lsu_wpt_match;
            lsu_mpu_status_q <= lsu_mpu_status;
       end
 
 (as that shows the intention more clearly that we try to capture the state during a 1-cycle rvalid pulse)      
       
assign lsu_valid = lsu_valid_q ? lsu_valid_q : lsu_valid_i;
assign lsu_wpt_match = lsu_valid_q ? lsu_wpt_match_q : lsu_wpt_match_i;
assign lsu_mpu_status = lsu_valid_q ? lsu_mpu_status_q : lsu_mpu_status_i;

2023-01-27 15:23 UTC, Silabs-ArjanB commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_wpt_match = lsu_wpt_match_i || lsu_wpt_match_q;
Line 126 should use the sticky version as well (i.e. lsu_mpu_status_i, lsu_wpt_match_i, lsu_valid_i are only allowed to be used in circuit that makes these signals sticky).

lsu_rdata_i usage needs comment why it is save to be used like that (without making it sticky); add assertion proving your assumption.

2023-01-27 15:23 UTC, Silabs-ArjanB commented on rtl/cv32e40x_core.sv
> +    .lsu_wpt_match_wb_i             ( wpt_match_wb           ),
lsu_err_wb signal needs comment why it is treated differently

2023-01-27 15:23 UTC, Silabs-ArjanB commented on sva/cv32e40x_wb_stage_sva.sv
> +  a_no_sticky_mpu_error:
Good to have this assertion. Are you only asserting it because this should not happen or is anything relying on this not happening (explain in the comment whether this is just how the design is expected to work or whether other parts of the design depend on this property).

2023-01-30 09:56 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    .lsu_mpu_status_wb_i            ( mpu_status_wb          ),
Fixed

2023-01-30 09:57 UTC, silabs-oysteink commented on rtl/cv32e40x_wpt.sv
> +   input logic  core_one_txn_pend_n,
Fixed

2023-01-30 09:57 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_wpt_match = lsu_wpt_match_i || lsu_wpt_match_q;
Fixed

2023-01-30 09:57 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +        lsu_valid_q <= lsu_valid;
Fixed

2023-01-30 09:58 UTC, silabs-oysteink commented on rtl/cv32e40x_wb_stage.sv
> +  assign lsu_wpt_match = lsu_wpt_match_i || lsu_wpt_match_q;
Update line 126 and added comments + assertion for lsu_rdata_i.

2023-01-30 09:58 UTC, silabs-oysteink commented on rtl/cv32e40x_core.sv
> +    .lsu_wpt_match_wb_i             ( wpt_match_wb           ),
Added comments

2023-01-30 09:59 UTC, silabs-oysteink commented on sva/cv32e40x_wb_stage_sva.sv
> +  a_no_sticky_mpu_error:
It is added to check the assumption it should never happen. I do think the existing comments cover that assumption?

2023-01-30 12:22 UTC, Silabs-ArjanB approved these changes

2023-01-30 12:22 UTC, merged