PUSH/POP not allowed outside of 'main' PMA regions
openhwgroup/cv32e40x pull request #772
Opened 2023-01-30 13:40 UTC by silabs-oysteink

2023-01-30 14:55 UTC, Silabs-ArjanB requested changes

2023-01-30 14:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_sequencer.sv
> +              seq_pushpop_o = 1'b1;
I prefer if illegal isntructions are excluded from having seq_push_pop_o set to 1. Same remark for line 191

2023-01-31 06:50 UTC, silabs-oysteink commented on rtl/cv32e40x_sequencer.sv
> +              seq_pushpop_o = 1'b1;
Agreed, fixed.

2023-01-31 07:59 UTC, Silabs-ArjanB approved these changes

2023-01-31 07:59 UTC, merged