Misaligned pointer update.
openhwgroup/cv32e40x pull request #812
Opened 2023-03-22 12:17 UTC by silabs-oysteink

Detecting misaligned pointers in the IF stage. Propagating alignment status down the pipeline and flagging exception code 0x0 if not ok.

Added assertions for checking that only mret pointers can cause misaligned instruction address exceptions. Added assertions to check that the alignment buffer only signal one valid for each pointer (currently failing), and that the alignment buffer must signal instr_valid_o if is not currently prefetching and the controller wants us to prefetch (currently failing).

The new and failing assertions will be addressed in a coming PR

2023-03-23 13:52 UTC, silabs-oivind commented on rtl/cv32e40x_alignment_buffer.sv
> +          if((resp_q[rptr].align_status != MPU_OK) || (resp_i.align_status != MPU_OK)) begin
MPU_OK -> ALIGN_OK

2023-03-23 14:01 UTC, silabs-oivind commented on rtl/cv32e40x_controller_fsm.sv
align_status should be checked wherever mpu_status is checked. Seems to be missing on line 1028:
            if (!(if_id_pipe_i.instr.bus_resp.err || (if_id_pipe_i.instr.mpu_status != MPU_OK))) begin // todo: add check for alignment check in IF (mret pointer)

2023-03-23 14:19 UTC, silabs-oivind requested changes
Please see comments in files.

2023-03-24 15:08 UTC, silabs-oysteink commented
Added four new commits:

1: Clearing of 'instr_is_*_ptr_o' flags in the alignment buffer. This ensure the IF stage does not see any pointer flags after a pointer has been sent from IF to ID. Not a real issue on E40X, but on E40S this could cause dummy instructions to be marked as pointers. SEC state unknown as it runs for a really long time.
2: Fixes according to review comments so far - not SEC clean as a check of align_status within the controller was added.
3: Fixed the issue where pointers could issue two instr_valid_o for the cases where the pointer itself looked like two compressed instructions. - Not SEC clean (bugfix)
4: Fixed an issue where the alignment buffer would deadlock for a misaligned pointer (it expected two responses). (Not SEC clean, bugfix)

The assertion 'a_no_outstanding_instr_valid attempts to check for deadlocks within the alignment buffer. If there are no outstanding requests or new requests being initiated, the alignment buffer must signal a valid instruction on instr_valid_o.

2023-03-24 15:09 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +                                   !(instr_is_clic_ptr_o || instr_is_mret_ptr_o || instr_is_tbljmp_ptr_o);
Not setting these signals for pointers ensure we never issue two instr_valid_o for pointers.

2023-03-24 15:10 UTC, silabs-oysteink commented on rtl/cv32e40x_alignment_buffer.sv
> +        instr_valid_o = valid;
Added to ensure we always signal valid for pointers, including misaligned ones.

2023-03-27 14:35 UTC, merged