Fix for issue #666.
openhwgroup/cv32e40x pull request #829
Opened 2023-04-13 08:20 UTC by silabs-oysteink

Added assertions to check that no synchronous events can be missed during any non-FUNCTIONAL FSM state.

2023-04-14 10:21 UTC, Silabs-ArjanB requested changes

2023-04-14 10:21 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    (pending_single_step || etrigger_in_wb)))
Although the following synchronous events are implied by the ones you listed, I would still add them explcitly everywhere for easier review:

          if (clic_ptr_in_id && id_valid_i && ex_ready_i) begin
          if (mret_in_wb && !ctrl_fsm_o.kill_wb) begin
          if (mret_ptr_in_wb && !ctrl_fsm_o.kill_wb && !exception_in_wb) begin
          if(clic_ptr_in_wb && !ctrl_fsm_o.kill_wb && !exception_in_wb) begin

2023-04-14 10:21 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +    // csr_flush_ack_q will be active during DEBUG_TAKEN.
It is unclear why it is okay to ignore this event. Needs explanation and an assertion.

2023-04-14 10:21 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +  // pending_single step may be true for the following conditions, but will not affect the debug cause:
Can you explain why it will not effect debug cause and can be ignored? (I think the simple reason is that this is the lowest priority debug entry reason, right?)

2023-04-17 08:14 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    (pending_single_step || etrigger_in_wb)))
Updated all the new assertions with these events.

2023-04-17 08:15 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +    // csr_flush_ack_q will be active during DEBUG_TAKEN.
Added explanation

2023-04-17 08:15 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +  // pending_single step may be true for the following conditions, but will not affect the debug cause:
Added explanation (debug_cause_q was decided the cycle before entering DEBUG_TAKEN state)

2023-04-17 09:45 UTC, Silabs-ArjanB approved these changes

2023-04-17 09:46 UTC, merged