Update to latest CLIC spec (Version 0.9-draft, 4/11/2023)
openhwgroup/cv32e40x pull request #837
Opened 2023-04-21 13:08 UTC by silabs-oysteink

- Removed alignment check from IF stage
- Removed exception code 0 (instruction address misaligned)
- Clearing mintthresh on mret into lower privilege
- Clearing mintthresh on dret into user mode
- Enforcing XLEN/8 alignment on pointer address when performing mret when mcause.minhv==1

2023-04-21 13:10 UTC, silabs-oysteink commented
Added the Do-not-merge label as merging this must be in sync with verification.

2023-04-24 07:15 UTC, Silabs-ArjanB requested changes

2023-04-24 07:15 UTC, Silabs-ArjanB commented on rtl/cv32e40x_if_stage.sv
> +    .bus_resp_i           ( bus_resp                    )
It seems prefetch_trans_ptr is unused now. Completely remove if that is true.

2023-04-24 07:37 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    .bus_resp_i           ( bus_resp                    )
It is unused by the design, but used by an assertion that is still relevant. I will check if I can rewrite the assertion or move this bit into helper logic.

2023-04-24 07:59 UTC, silabs-oysteink commented on rtl/cv32e40x_if_stage.sv
> +    .bus_resp_i           ( bus_resp                    )
Removed signal from prefetcher. SEC clean

2023-05-10 10:40 UTC, silabs-oivind commented on rtl/cv32e40x_cs_registers.sv
> +
Non-blocking assignment in combinational block.

2023-05-10 10:40 UTC, silabs-oivind commented on rtl/cv32e40x_cs_registers.sv
> +          end
Non-blocking assignment in combinational block.

2023-05-10 10:46 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +
Fixed

2023-05-10 10:46 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +          end
Fixed

2023-05-10 11:07 UTC, Silabs-ArjanB approved these changes

2023-05-23 10:35 UTC, silabs-oysteink commented
Closing PR and making a new one after rebasing the changes in this PR on top of the current master.

2023-05-23 10:35 UTC, closed without merging