Update rvfi_mem interface.
openhwgroup/cv32e40x pull request #841
Opened 2023-04-28 07:35 UTC by silabs-oivind

Fix 3 issues:
1. Transfers could be missed if there's backpressure from WB when lsu_data_trans_valid is asserted.
2. If the 2nd half of a split misaligned transfer is blocked, it would still be reported on rvfi_mem.
3. rvfi_mem_rdata was not correct for split misaligned transfers. Only rdata from 1st transfer would be reported on rvfi_mem

The bugs fixed in this PR were found by assertions written for https://github.com/openhwgroup/cv32e40x/issues/648
The PR for these assertions will follow.

2023-04-28 09:08 UTC, silabs-oysteink requested changes

2023-04-28 11:10 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +        // Update rvfi_mem
Updated comment.

2023-04-28 12:45 UTC, silabs-oysteink approved these changes

2023-05-02 07:51 UTC, Silabs-ArjanB requested changes

2023-05-02 07:51 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +  // Return byte-mask for bytes that would be part of the 2nd transfer in a split transfer.
This mask does not seem to take into account a split halfword transfer. Also order of bits seems reversed (if not, add explanation why it is okay)

2023-05-02 09:05 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +  // Return byte-mask for bytes that would be part of the 2nd transfer in a split transfer.
Added comments to clarify.

2023-05-02 09:06 UTC, Silabs-ArjanB approved these changes

2023-05-02 09:07 UTC, Silabs-ArjanB approved these changes

2023-05-02 09:07 UTC, merged