Fix for issue #619
openhwgroup/cv32e40x pull request #863
Opened 2023-05-30 09:06 UTC by silabs-oysteink

Issue was mostly fixed from before, but this PR should hopefully close the last items/todo's.

2023-05-30 10:54 UTC, Silabs-ArjanB requested changes

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !sequence_interruptible &&  // Sequence is in progress (first_op done in WB)
Can't you describe this assertion without using the sequence_interruptible signal (as that is also not part of the comment and it is a much stronger precondition than just using first/last signals as would be the thing to do if you implement what the comment states)

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                     ((debug_cause_q == DBG_CAUSE_STEP) && (last_op_wb_i) && sequence_interruptible))) // Or we finished single stepping the instruction
This handling of single step looks a bit weird. Basically this is just about entering debug after finishing an instruction. That is not special as async debug entry is allowed then as well. I think this has to do with the sequence_interruptible precondition. Will further comment after the fix related to sequence_interruptible.

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !sequence_interruptible &&  // Sequence is in progress (first_op done in WB)
Same remarks here about sequence_interruptible and single stepping

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_controller_fsm_sva.sv
> +    else `uvm_error("controller", "WB killed while sequence was in progress")
Same here

2023-05-30 10:54 UTC, Silabs-ArjanB commented on bhv/cv32e40x_wrapper.sv
> +                .mret_pointer_if_i                (core_i.if_stage_i.prefetch_is_mret_ptr),
Irregular renaming

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_core_sva.sv
> +    a_single_step__minhv_no_irq_if :
a_single_step__minhv_no_irq_if -> a_single_step_minhv_no_irq_if

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_core_sva.sv
> +                    (inst_taken_id && dcsr.step && !ctrl_fsm.debug_mode)
disable iff should only depend on reset signal

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_core_sva.sv
> +    assert property (@(posedge clk) disable iff (!rst_ni || interrupt_taken)
disable iff should only depend on reset signal

2023-05-30 10:54 UTC, Silabs-ArjanB commented on sva/cv32e40x_core_sva.sv
> +      else `uvm_error("core", "More than one instruction issued from IF to ID during single step")
Fix error message

2023-06-02 08:22 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !sequence_interruptible &&  // Sequence is in progress (first_op done in WB)
Changed to using 'sequence_in_progress_wb'.

2023-06-02 08:22 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                     ((debug_cause_q == DBG_CAUSE_STEP) && (last_op_wb_i) && sequence_interruptible))) // Or we finished single stepping the instruction
Discussed offline, should be ok.

2023-06-02 08:22 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +                    !sequence_interruptible &&  // Sequence is in progress (first_op done in WB)
Updated

2023-06-02 08:22 UTC, silabs-oysteink commented on sva/cv32e40x_controller_fsm_sva.sv
> +    else `uvm_error("controller", "WB killed while sequence was in progress")
Updated

2023-06-02 08:22 UTC, silabs-oysteink commented on sva/cv32e40x_core_sva.sv
> +    a_single_step__minhv_no_irq_if :
Renamed

2023-06-02 08:23 UTC, silabs-oysteink commented on sva/cv32e40x_core_sva.sv
> +    assert property (@(posedge clk) disable iff (!rst_ni || interrupt_taken)
Fixed

2023-06-02 08:24 UTC, silabs-oysteink commented on sva/cv32e40x_core_sva.sv
> +                    cs_registers_mcause_q.minhv
Refactored assertion to not include mcause.minhv

2023-06-02 10:13 UTC, merged