Fixed todo's related to mul_en/div_en i EX stage
openhwgroup/cv32e40x pull request #902
Opened 2023-08-08 12:40 UTC by silabs-oysteink

Factored halt_ex/kill_ex out of mul_en and div_en - multiplier and divider now handles them theirselves.
In the divider, div_en_i and valid_i was then duplicates, changed to using only valid_i.

SEC clean (with multiplier operation converted to add to enable converging SEC)

2023-08-14 10:52 UTC, Silabs-ArjanB requested changes

2023-08-14 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mult.sv
> +    // is handled after the case statement.
Remove comment (no longer accurate)

2023-08-14 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mult.sv
> +            ready_o       = !halt_i || kill_i;
Normally we would set ready_o = 1 upon kill even if ready_i=0. Would that be SEC clean as well?

2023-08-14 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mult.sv
> +      if ((valid_i && !halt_i) || kill_i) begin
Above mulh_state_next is changed also for !valid, but here that scenario is not handled

2023-08-14 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_div.sv
> +          ready_o    = !halt_i || kill_i;
Same remark as for multiplier

2023-08-14 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40x_div.sv
> +      if ((valid_i && !halt_i) || kill_i) begin
Same remark as for multiplier

2023-08-14 10:56 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +    // is handled after the case statement.
Removed comment.

2023-08-14 10:56 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +            ready_o       = !halt_i || kill_i;
I will check :)

2023-08-14 13:11 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +            ready_o       = !halt_i || kill_i;
Updated, SEC clean.

2023-08-14 13:12 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +          ready_o         = !halt_i || kill_i;
Updated code, SEC clean.

2023-08-14 13:12 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +      if ((valid_i && !halt_i) || kill_i) begin
Fixed, SEC clean.

2023-08-14 13:12 UTC, silabs-oysteink commented on rtl/cv32e40x_div.sv
> +          ready_o    = !halt_i || kill_i;
Fixed, SEC clean.

2023-08-14 13:12 UTC, silabs-oysteink commented on rtl/cv32e40x_div.sv
> +      if ((valid_i && !halt_i) || kill_i) begin
Fixed, SEC clean.

2023-08-15 11:58 UTC, Silabs-ArjanB requested changes

2023-08-15 11:58 UTC, Silabs-ArjanB commented on rtl/cv32e40x_div.sv
> +        ready_o = (ready_i && !halt_i) || kill_i;
Now halt impacts ready_o but not next_state. I see that next-state is not used later on in that case, but it is just difficult to understand like this.

Maybe keep case statement as in original design and assume valid_i=1, halt_i=0, kill_i=0 within the case and deal with exceptions to that assumption after the case statement.

2023-08-15 11:58 UTC, Silabs-ArjanB commented on rtl/cv32e40x_mult.sv
> +    // is handled after the case statement.
Comment seems still there

2023-08-17 11:21 UTC, silabs-oysteink commented on rtl/cv32e40x_div.sv
> +        ready_o = (ready_i && !halt_i) || kill_i;
Reverted to original case statement.

2023-08-25 08:02 UTC, Silabs-ArjanB requested changes

2023-08-25 08:59 UTC, silabs-oysteink commented on rtl/cv32e40x_mult.sv
> +        valid_o = 1'b0;
Fixed

2023-08-25 09:07 UTC, merged