Optimized CSR stalls
openhwgroup/cv32e40x pull request #917
Opened 2023-08-24 08:03 UTC by silabs-oysteink

Conservatively stalling ID for any implicit CSR read while any implicit or explicit CSR write is in EX or WB (unchanged)
Conservatively stalling EX for any implicit CSR read while any implicit or explicit CSR write is in WB
Conservatively stalling EX for any explicit CSR rad while any implicit CSR write is in WB
Precisely stalling EX for any explicit CSR read while an explicit CSR write to the same CSR is in WB.

2023-08-25 09:55 UTC, Silabs-ArjanB requested changes

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +    csr_hz_o.impl_wr_ex = 1'b0;
new line after this

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_wr_ex = 1'b1; // Writes to mcause aswell
aswell -> as well

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_re_ex = 1'b1; // Reads mstatus
also reads mscratch (update comment and spreadsheet)

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_re_ex = 1'b1; // Reads mcause and mintstatus
also reads mscratch (update comment and spreadsheet)

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_re_ex = id_ex_pipe_i.csr_en && id_ex_pipe_i.instr_valid;
Add note here and in package file that this signal is conservative as it uses registered instr_valid 
Here also add note why that is okay.

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_we_ex = ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid && (csr_op != CSR_OP_READ);
Same remark as above

2023-08-25 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_we_ex = ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid && (csr_op != CSR_OP_READ);
Mixing signals with different timing, not okay, also does not match package file description of what expl_we_ex means

2023-08-25 10:25 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +    csr_hz_o.impl_wr_ex = 1'b0;
Fixed

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_wr_ex = 1'b1; // Writes to mcause aswell
Fixed

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_re_ex = 1'b1; // Reads mstatus
Updated both

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +          csr_hz_o.impl_re_ex = 1'b1; // Reads mcause and mintstatus
Updated

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_re_ex = id_ex_pipe_i.csr_en && id_ex_pipe_i.instr_valid;
Adde comment.

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_we_ex = ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid && (csr_op != CSR_OP_READ);
Fixed

2023-08-25 10:26 UTC, silabs-oysteink commented on rtl/cv32e40x_cs_registers.sv
> +  assign csr_hz_o.expl_we_ex = ex_wb_pipe_i.csr_en && ex_wb_pipe_i.instr_valid && (csr_op != CSR_OP_READ);
Renamed to expl_we_wb and expl_waddr_wb

2023-08-25 15:01 UTC, Silabs-ArjanB requested changes

2023-08-28 07:23 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  assign csr_unqual_id = sys_mret_unqual_id || tbljmp_unqual_id;
Renamed

2023-08-28 07:23 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  // Detect any implicit CSR write in EX
Updated comment

2023-08-28 07:24 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +                                    id_ex_pipe_i.csr_en && csr_hz_i.impl_wr_ex));
Added brackets

2023-08-28 07:24 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +                                 (((ex_wb_pipe_i.sys_en && ex_wb_pipe_i.sys_mret_insn) || ex_wb_pipe_i.instr_meta.clic_ptr || ex_wb_pipe_i.instr_meta.mret_ptr) ||
Added brackets

2023-08-28 07:24 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  assign csr_write_in_ex = (id_ex_pipe_i.instr_valid && (id_ex_pipe_i.csr_en || csr_impl_write_in_ex));
Removed

2023-08-28 07:24 UTC, silabs-oysteink commented on rtl/cv32e40x_controller_bypass.sv
> +  assign csr_write_in_wb = (ex_wb_pipe_i.instr_valid && (ex_wb_pipe_i.csr_en || csr_impl_write_in_wb));
Removed

2023-08-28 07:32 UTC, Silabs-ArjanB approved these changes

2023-08-28 07:33 UTC, merged