Rvfi mem exokay and err
openhwgroup/cv32e40x pull request #947
Opened 2023-09-13 09:53 UTC by silabs-krdosvik

Added rvfi_mem_exokay and rvfi_mem_err.

Formal compiles.
ci_check is green except from the clic and debug_test2 tests which seem to be affected by something else.

2023-09-13 10:25 UTC, silabs-oysteink approved these changes

2023-09-13 12:07 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
mem_rmask/wmask are multibit signals, but used as if they were single bit.

2023-09-13 12:09 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
Usage of lsu_err_wb_i[0] is not correct for e40s. On e40s, lsu_err is of type lsu_err_wb_t (not logic [1:0] as it is on e40x).
@silabs-oysteink , did we have a plan to get e40s and e40x in sync here?

2023-09-13 12:10 UTC, silabs-oysteink commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
I think we need to introduce a similar type on e40x. I suggest we do that after this PR is merged (also to S)

2023-09-13 12:16 UTC, silabs-oivind commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
Sounds good.

2023-09-13 13:33 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
Good points!

2023-09-14 07:36 UTC, silabs-oivind commented on sva/cv32e40x_rvfi_sva.sv
> +        data_obi_resp_fifo[wr_resp_ptr].err <= {1'b0, m_c_obi_data_if.resp_payload.err[0]};
Should not need to assign .err explicitly. It's already handled by the assignment above.

2023-09-14 07:37 UTC, silabs-oivind commented on sva/cv32e40x_rvfi_sva.sv
> +
rvfi_mem_exp.err is single bit, data_obi_resp_fifo is 2 bits. Bit 0 should be used.

2023-09-14 07:38 UTC, silabs-oivind commented on sva/cv32e40x_rvfi_sva.sv
> +
slit_*_err is single bit. data_obi_resp_fifo is 2 bits.

2023-09-14 07:40 UTC, silabs-oivind commented on sva/cv32e40x_rvfi_sva.sv
> +          rvfi_mem_exp.exokay [(1*i_memop)  +: 1]  = data_obi_resp_fifo[rd_ptr_memop].exokay;
Is it true that exokay is always equal for both transfers in a split transfer?

2023-09-14 07:42 UTC, silabs-oivind requested changes
See inline comments

2023-09-14 09:55 UTC, silabs-krdosvik commented on sva/cv32e40x_rvfi_sva.sv
> +        data_obi_resp_fifo[wr_resp_ptr].err <= {1'b0, m_c_obi_data_if.resp_payload.err[0]};
True! Thanks for noticing.

2023-09-14 09:58 UTC, silabs-krdosvik commented on sva/cv32e40x_rvfi_sva.sv
> +
Thanks for noticing.

2023-09-14 10:06 UTC, silabs-krdosvik commented on sva/cv32e40x_rvfi_sva.sv
> +          rvfi_mem_exp.exokay [(1*i_memop)  +: 1]  = data_obi_resp_fifo[rd_ptr_memop].exokay;
Requirements for atomic is that the address is naturally aligned, so no split transfers I believe. Misaligned address should generate an exception.

2023-09-14 11:54 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_err   [ (2*(memop_cnt+1))-1 -:  2] <= (mem_rmask [STAGE_WB] || (mem_wmask [STAGE_WB] && ex_mem_trans.atop[5])) ? lsu_err_wb_i[0] : '0;
Since it is non-blocking I will use the right hand side of the expression for rvfi_mem_r/wmask

2023-09-14 11:58 UTC, silabs-oivind approved these changes

2023-09-14 12:09 UTC, silabs-oysteink approved these changes

2023-09-14 16:29 UTC, Silabs-ArjanB requested changes

2023-09-15 06:33 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +        // Report OBI exokay and err on rvfi for all read transaction, but only for atomic write transaction
Oh... Thanks for noticing!

2023-09-15 13:35 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_exokay[ (1*(memop_cnt+1))-1 -:  1] <= ((|mem_rmask [STAGE_WB] && !mem_access_blocked_wb) || (|mem_wmask [STAGE_WB] && !mem_access_blocked_wb && ex_mem_trans.atop[5])) ? lsu_exokay_wb
Agreed!

2023-09-15 15:23 UTC, Silabs-ArjanB requested changes

2023-09-15 15:23 UTC, Silabs-ArjanB commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_exokay[ (1*(memop_cnt+1))-1 -:  1] <= ((|mem_rmask [STAGE_WB] && !mem_access_blocked_wb) || (|mem_wmask [STAGE_WB] && !mem_access_blocked_wb && (!ex_mem_trans.memtype[1] || ex_mem_tr
- memtype[0] relates to bufferable, not the memtype[1] bit
- I would also expect that sva/cv32e40x_rvfi_sva.sv gets updated with checks related to non-bufferable writes

2023-09-15 16:12 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +        rvfi_mem_exokay[ (1*(memop_cnt+1))-1 -:  1] <= ((|mem_rmask [STAGE_WB] && !mem_access_blocked_wb) || (|mem_wmask [STAGE_WB] && !mem_access_blocked_wb && (!ex_mem_trans.memtype[1] || ex_mem_tr
Oh, that is embarrassing. Good point!

2023-09-19 10:09 UTC, Silabs-ArjanB requested changes

2023-09-19 10:09 UTC, Silabs-ArjanB commented on rtl/cv32e40x_lsu_response_filter.sv
> +  assign resp_o.exokay = (resp_valid_i && resp_i.exokay);
exokay should be used similar to rdata and not be qualified with the timing critical resp_valid_i signal

2023-09-19 20:24 UTC, silabs-krdosvik commented on rtl/cv32e40x_lsu_response_filter.sv
> +  assign resp_o.exokay = (resp_valid_i && resp_i.exokay);
I see, okay.

2023-09-22 12:43 UTC, silabs-krdosvik commented on bhv/cv32e40x_rvfi.sv
> +          rvfi_mem_err     [ (1*(memop_cnt+1))-1 -:  1] <= rvfi_mem_err   [ (1'b1*(memop_cnt+1'b1))-1'b1 -:  1] || ((|mem_rmask [STAGE_WB] || (|mem_wmask [STAGE_WB] && !ex_mem_trans_2.memtype[0])) ?
Used 1'b1 instead of 1 since 1 is a 32 bit signal, and using that convert the index signal to a 32 bit signal. Formal gave a warning that said that indexing of the rvfi_mem_err/exokay could go out of range (even though it will not) (since the indexing is a 32 bit signal instead of a 7 bit signal). Writing the 1s as 1'b1s removed the warning.

2023-09-26 17:41 UTC, silabs-oysteink approved these changes

2023-09-27 06:21 UTC, Silabs-ArjanB approved these changes

2023-09-27 06:21 UTC, merged