Parameterize Zicntr and Xif features
openhwgroup/cv32e40x pull request #951
Opened 2023-09-15 13:26 UTC by silabs-halfdan

Parameterized Zicntr only registers.
Parameterized speculative reads for Xif.

LEC clean with ZICNTR=1'b1 and X_EXT=1'b1.

Logically equivalent to cv32e40s with all core exclusive features disabled (ZICNTR=1'b0, X_EXT=1'b0, etc.).

2023-09-15 15:46 UTC, Silabs-ArjanB requested changes

2023-09-15 15:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +        if (ZICNTR) begin : zicntr_counters
ZICNTR is a misleading name. Please rename all ZICNTR and *zicntr* to ZICNTR_ZIHPM  and *zicntr_zihpm* respectively. Or separate ZICNTR and ZIHPM local parameters

2023-09-15 15:46 UTC, Silabs-ArjanB commented on rtl/cv32e40x_cs_registers.sv
> +          csr_rdata_int       = mhpmcounter_rdata[csr_raddr[4:0]][63:32];
One less space before =

2023-09-18 07:13 UTC, silabs-halfdan commented on rtl/cv32e40x_cs_registers.sv
> +        if (ZICNTR) begin : zicntr_counters
Good point, will parameterize them separately.

2023-09-18 09:48 UTC, Silabs-ArjanB approved these changes

2023-09-18 09:49 UTC, merged